"use strict";
const path=require("node:path");const {loadRuntimeEnv}=require("../../../lib/runtimeEnv");
loadRuntimeEnv({defaultCandidates:[path.join(__dirname,"..",".env"),path.join(__dirname,"..","..",".env")]});
const {ensureRedisConnected}=require("./config/redis");const {closeQueues,queueNames}=require("./queues/magaluQueue");const {startTokenRefreshWorker,stopTokenRefreshWorker}=require("./jobs/tokenRefresh.worker");const {startCatalogSyncWorker,stopCatalogSyncWorker}=require("./jobs/catalogSync.worker");const {startWebhookProcessWorker,stopWebhookProcessWorker}=require("./jobs/webhookProcess.worker");const {startPriceUpdateWorker,stopPriceUpdateWorker}=require("./jobs/priceUpdate.worker");const {startStockUpdateWorker,stopStockUpdateWorker}=require("./jobs/stockUpdate.worker");const {startHubResourceSyncWorker,stopHubResourceSyncWorker}=require("./jobs/hubResourceSync.worker");
const HEARTBEAT_KEY="magalu:worker:heartbeat",HEARTBEAT_TTL_SECONDS=60;let timer=null;
async function writeHeartbeat(redis){await redis.set(HEARTBEAT_KEY,JSON.stringify({ts:Date.now(),worker:"seller-magalu",queues:Object.values(queueNames),stage:4,processors:Object.values(queueNames)}),"EX",HEARTBEAT_TTL_SECONDS);}
async function main(){const redis=await ensureRedisConnected();await startTokenRefreshWorker();await startCatalogSyncWorker();await startWebhookProcessWorker();await startPriceUpdateWorker();await startStockUpdateWorker();await startHubResourceSyncWorker();await writeHeartbeat(redis);timer=setInterval(()=>void writeHeartbeat(redis).catch(e=>console.error("[seller-magalu-worker] heartbeat failed",e?.message||e)),10000);timer.unref?.();console.log("[seller-magalu-worker] protected writes ready",{stage:5,queues:Object.values(queueNames),note:"Preço/estoque protegidos e recursos de conta sincronizados com o Hub."});}
async function shutdown(signal){console.log(`[seller-magalu-worker] received ${signal}, shutting down...`);if(timer)clearInterval(timer);await Promise.all([stopHubResourceSyncWorker().catch(()=>{}),stopStockUpdateWorker().catch(()=>{}),stopPriceUpdateWorker().catch(()=>{}),stopWebhookProcessWorker().catch(()=>{}),stopCatalogSyncWorker().catch(()=>{}),stopTokenRefreshWorker().catch(()=>{})]);await closeQueues().catch(()=>{});process.exit(0);}
process.on("SIGTERM",()=>void shutdown("SIGTERM"));process.on("SIGINT",()=>void shutdown("SIGINT"));process.on("unhandledRejection",e=>console.error("[seller-magalu-worker] unhandled rejection",e));process.on("uncaughtException",e=>{console.error("[seller-magalu-worker] uncaught exception",e);process.exit(1);});main().catch(e=>{console.error("[seller-magalu-worker] bootstrap failed",e);process.exit(1);});
