"use strict";
const env=require("../config/env");
const accountRepository=require("../repositories/accountRepository");
const orderRepository=require("../repositories/orderRepository");
const writeRepository=require("../repositories/deliveryWriteRepository");
const {appendAuditEvent}=require("../repositories/auditRepository");
const {checkAccountAccess}=require("../services/hubResourceAccessService");
const remote=require("../services/deliveryWriteRemoteService");
const {ACTIONS,INVOICE_READ_SCOPE,requiredScopes,hasScopes,normalizeAction,snapshot,normalizeInvoiceInput,normalizeFinishInput,sanitizeRemote}=require("../services/deliveryWritePayload");
const {enqueueDeliveryWriteOperation}=require("../queues/magaluQueue");
function int(v){const n=Number.parseInt(String(v==null?"":v),10);return Number.isFinite(n)&&n>0?n:null;}
function text(v,max=500){return String(v==null?"":v).trim().slice(0,max);}
function fail(res,error,fallback){const status=Number(error?.status)||500;return res.status(status).json({ok:false,error:error?.code||"MAGALU_DELIVERY_WRITE_ERROR",message:status>=500?fallback:(error?.message||fallback)});}
async function accountFor(req,{write=false,force=false}={}){const accountId=int(req.query?.account_id||req.body?.account_id||req.params?.accountId);if(!accountId){const e=new Error("account_id inválido.");e.status=400;e.code="MAGALU_ACCOUNT_ID_REQUIRED";throw e;}const identity=req.magaluIdentity,account=await accountRepository.findAccountByIdForTenant(accountId,identity.dachTenantId);if(!account){const e=new Error("Conta Magalu não encontrada para esta empresa.");e.status=404;e.code="MAGALU_ACCOUNT_NOT_FOUND";throw e;}if(String(account.status)!=="active"){const e=new Error("A conta Magalu não está ativa.");e.status=409;e.code="MAGALU_ACCOUNT_INACTIVE";throw e;}const hub=await checkAccountAccess(identity,account,{action:write?"WRITE magalu":"READ magalu",force});if(!hub.allow){const e=new Error("O Hub não confirmou acesso a esta conta Magalu.");e.status=403;e.code=write?"MAGALU_DELIVERY_HUB_WRITE_DENIED":"MAGALU_DELIVERY_HUB_READ_DENIED";throw e;}return account;}
async function localDelivery(account,id){const delivery=await orderRepository.getDelivery(account.id,text(id,300));if(!delivery){const e=new Error("Entrega ainda não existe na réplica local. Reconciliе o pedido primeiro.");e.status=404;e.code="MAGALU_DELIVERY_LOCAL_NOT_FOUND";throw e;}if(!delivery.channel_id){const e=new Error("Entrega sem channel_id; não é seguro executar ações remotas.");e.status=409;e.code="MAGALU_DELIVERY_CHANNEL_MISSING";throw e;}return delivery;}
function scopeStatus(account){return{invoice_read:{scope:INVOICE_READ_SCOPE,ok:hasScopes(account,[INVOICE_READ_SCOPE])},invoice_write:{enabled:env.MAGALU_INVOICE_WRITE_ENABLED===true,required:requiredScopes(ACTIONS.INVOICE),ok:hasScopes(account,requiredScopes(ACTIONS.INVOICE))},finish_write:{enabled:env.MAGALU_DELIVERY_WRITE_ENABLED===true,required:requiredScopes(ACTIONS.FINISH),ok:hasScopes(account,requiredScopes(ACTIONS.FINISH))}};}
async function status(req,res){try{const account=await accountFor(req);return res.json({ok:true,preview_ttl_seconds:env.MAGALU_DELIVERY_WRITE_PREVIEW_TTL_SECONDS,verify_attempts:env.MAGALU_DELIVERY_WRITE_VERIFY_ATTEMPTS,invoice_xml_max_bytes:env.MAGALU_INVOICE_XML_MAX_BYTES,scopes:scopeStatus(account),features:{invoice_send:env.MAGALU_INVOICE_WRITE_ENABLED===true,finish_delivery:env.MAGALU_DELIVERY_WRITE_ENABLED===true,ship_delivery:false,label_generation:false}});}catch(error){return fail(res,error,"Não foi possível carregar o status de Expedição.");}}
async function history(req,res){try{const account=await accountFor(req);const delivery=await localDelivery(account,req.params.deliveryId);const response=await remote.getHistory(account,delivery.remote_id,delivery.channel_id);return res.json({ok:true,delivery_id:delivery.remote_id,status:response.status,request_id:response.requestId||null,data:sanitizeRemote(response.data)||null});}catch(error){return fail(res,error,"Não foi possível consultar o histórico da entrega.");}}
async function invoices(req,res){try{const account=await accountFor(req);if(!hasScopes(account,[INVOICE_READ_SCOPE]))return res.status(409).json({ok:false,error:"MAGALU_INVOICE_READ_SCOPE_MISSING",message:`Scope ausente: ${INVOICE_READ_SCOPE}.`});const delivery=await localDelivery(account,req.params.deliveryId);const response=await remote.getInvoices(account,delivery.remote_id,delivery.channel_id);return res.json({ok:true,delivery_id:delivery.remote_id,status:response.status,request_id:response.requestId||null,data:sanitizeRemote(response.data)||null});}catch(error){return fail(res,error,"Não foi possível consultar NF-es da entrega.");}}
async function preview(req,res){try{const account=await accountFor(req,{write:true,force:true}),identity=req.magaluIdentity,action=normalizeAction(req.body?.action),delivery=await localDelivery(account,req.body?.delivery_id);if(!hasScopes(account,requiredScopes(action))){const e=new Error(`Scopes ausentes para ${action}. Reconecte a conta após liberar as permissões no aplicativo Magalu.`);e.status=409;e.code="MAGALU_DELIVERY_WRITE_SCOPE_MISSING";throw e;}const currentResponse=await remote.getDelivery(account,delivery.remote_id,delivery.channel_id),before=snapshot(currentResponse.data||{},delivery);if(action===ACTIONS.INVOICE&&before.status!=="approved"){const e=new Error("Envio de NF-e protegido exige entrega em status approved.");e.status=409;e.code="MAGALU_INVOICE_DELIVERY_NOT_APPROVED";throw e;}if(action===ACTIONS.INVOICE&&delivery.is_fulfillment===true){const e=new Error("Pedidos Fulfillment têm NF-e emitida pelo CD; este fluxo não envia NF-e para fulfillment.");e.status=409;e.code="MAGALU_INVOICE_FULFILLMENT_BLOCKED";throw e;}if(action===ACTIONS.FINISH&&before.status!=="shipped"){const e=new Error("Finalização protegida exige entrega em status shipped.");e.status=409;e.code="MAGALU_FINISH_DELIVERY_NOT_SHIPPED";throw e;}const normalized=action===ACTIONS.INVOICE?normalizeInvoiceInput(req.body?.invoice||{},before.channel_id,{maxXmlBytes:env.MAGALU_INVOICE_XML_MAX_BYTES}):normalizeFinishInput(req.body?.finish||{},before.channel_id);const saved=await writeRepository.createPreview({accountId:account.id,dachTenantId:identity.dachTenantId,dachUserId:identity.dachUserId,delivery:{...delivery,...before},action,requestBody:normalized.body,requestedMetadata:normalized.metadata});await appendAuditEvent({action:"DELIVERY_WRITE_PREVIEW_CREATED",category:"write",outcome:"success",accountId:account.id,dachTenantId:identity.dachTenantId,dachUserId:identity.dachUserId,magaluTenantId:account.magalu_tenant_id,resourceType:"delivery",source:"orders-ui",details:{preview_id:saved.id,delivery_id:saved.delivery_id,order_code:saved.order_code,action:saved.action,requested_metadata:saved.requested_metadata}}).catch(()=>{});return res.json({ok:true,preview:saved,write_enabled:action===ACTIONS.INVOICE?env.MAGALU_INVOICE_WRITE_ENABLED:env.MAGALU_DELIVERY_WRITE_ENABLED});}catch(error){return fail(res,error,"Não foi possível gerar o preview de expedição.");}}
async function apply(req,res){try{const identity=req.magaluIdentity,preview=await writeRepository.getPreview(req.body?.preview_id,{dachTenantId:identity.dachTenantId,dachUserId:identity.dachUserId});if(!preview)return res.status(404).json({ok:false,error:"MAGALU_DELIVERY_PREVIEW_NOT_FOUND"});const account=await accountRepository.findAccountByIdForTenant(preview.account_id,identity.dachTenantId);if(!account)return res.status(404).json({ok:false,error:"MAGALU_ACCOUNT_NOT_FOUND"});const enabled=preview.action===ACTIONS.INVOICE?env.MAGALU_INVOICE_WRITE_ENABLED===true:env.MAGALU_DELIVERY_WRITE_ENABLED===true;if(!enabled)return res.status(409).json({ok:false,error:"MAGALU_DELIVERY_WRITE_DISABLED",message:"A escrita desta ação está desabilitada. O preview pode ser revisado sem executar POST remoto."});const hub=await checkAccountAccess(identity,account,{action:"WRITE magalu",force:true});if(!hub.allow)return res.status(403).json({ok:false,error:"MAGALU_DELIVERY_HUB_WRITE_DENIED"});if(!hasScopes(account,requiredScopes(preview.action)))return res.status(409).json({ok:false,error:"MAGALU_DELIVERY_WRITE_SCOPE_MISSING"});const op=await writeRepository.createOperationFromPreview(preview.id,{dachTenantId:identity.dachTenantId,dachUserId:identity.dachUserId});const job=await enqueueDeliveryWriteOperation(op,{reason:"apply"});await appendAuditEvent({action:"DELIVERY_WRITE_QUEUED",category:"write",outcome:"success",accountId:op.account_id,dachTenantId:op.dach_tenant_id,dachUserId:identity.dachUserId,magaluTenantId:account.magalu_tenant_id,resourceType:"delivery",batchId:`delivery:${op.id}`,source:"orders-ui",details:{operation_id:op.id,delivery_id:op.delivery_id,order_code:op.order_code,action:op.action,job_id:job?.id||null}}).catch(()=>{});return res.status(202).json({ok:true,operation:op,job_id:job?.id||null});}catch(error){return fail(res,error,"Não foi possível enfileirar a operação de entrega.");}}
async function operations(req,res){try{await accountFor(req);return res.json({ok:true,...await writeRepository.list(req.magaluIdentity.dachTenantId,{accountId:req.query?.account_id,status:req.query?.status,action:req.query?.action,page:req.query?.page,limit:req.query?.limit})});}catch(error){return fail(res,error,"Não foi possível listar as operações de entrega.");}}
async function operation(req,res){try{const op=await writeRepository.getOperationForTenant(req.params.operationId,req.magaluIdentity.dachTenantId);if(!op)return res.status(404).json({ok:false,error:"MAGALU_DELIVERY_OPERATION_NOT_FOUND"});return res.json({ok:true,operation:writeRepository.publicOperation(op)});}catch(error){return fail(res,error,"Não foi possível abrir a operação.");}}
async function reverify(req,res){try{const identity=req.magaluIdentity,op=await writeRepository.getOperationForTenant(req.params.operationId,identity.dachTenantId);if(!op)return res.status(404).json({ok:false,error:"MAGALU_DELIVERY_OPERATION_NOT_FOUND"});if(!["uncertain","divergent"].includes(String(op.status)))return res.status(409).json({ok:false,error:"MAGALU_DELIVERY_REVERIFY_INVALID_STATE",message:"Somente operações uncertain/divergent podem ser reverificadas."});const account=await accountRepository.findAccountByIdForTenant(op.account_id,identity.dachTenantId);if(!account)return res.status(404).json({ok:false,error:"MAGALU_ACCOUNT_NOT_FOUND"});const hub=await checkAccountAccess(identity,account,{action:"READ magalu",force:true});if(!hub.allow)return res.status(403).json({ok:false,error:"MAGALU_DELIVERY_HUB_READ_DENIED"});const job=await enqueueDeliveryWriteOperation(op,{reason:"reverify"});await appendAuditEvent({action:"DELIVERY_WRITE_REVERIFY_REQUESTED",category:"write",outcome:"info",accountId:op.account_id,dachTenantId:op.dach_tenant_id,dachUserId:identity.dachUserId,resourceType:"delivery",batchId:`delivery:${op.id}`,requestId:op.request_id||null,source:"orders-ui",details:{operation_id:op.id,delivery_id:op.delivery_id,action:op.action,previous_status:op.status,mode:"verification_only",job_id:job?.id||null}}).catch(()=>{});return res.status(202).json({ok:true,queued:true,operation_id:op.id,job_id:job?.id||null,mode:"verification_only"});}catch(error){return fail(res,error,"Não foi possível reverificar a operação.");}}
module.exports={status,history,invoices,preview,apply,operations,operation,reverify,_test:{int,text,scopeStatus}};
