"use strict";

const env = require("../config/env");
const accountRepository = require("../repositories/accountRepository");
const skuMassRepository = require("../repositories/skuMassRepository");
const { appendAuditEvent } = require("../repositories/auditRepository");
const { checkAccountAccess } = require("../services/hubResourceAccessService");
const remote = require("../services/skuRemoteService");
const { hasWriteScope, WRITE_SCOPE } = require("../services/skuMassPayload");
const { enqueueSkuMassItems, enqueueSkuMassReverify } = require("../queues/magaluQueue");

function int(value){const n=Number.parseInt(String(value==null?"":value),10);return Number.isFinite(n)&&n>0?n:null;}
function text(value,max=500){return String(value==null?"":value).trim().slice(0,max);}
function fail(res,error,fallback){const status=Number(error?.status)||500;return res.status(status).json({ok:false,error:error?.code||"MAGALU_SKU_MANAGEMENT_ERROR",message:status>=500?fallback:(error?.message||fallback)});}
async function accountFor(req,{write=false,force=false,accountIdOverride=null}={}){
  const accountId=int(accountIdOverride||req.query?.account_id||req.body?.account_id||req.params?.accountId);
  if(!accountId){const e=new Error("account_id inválido.");e.status=400;e.code="MAGALU_ACCOUNT_ID_REQUIRED";throw e;}
  const identity=req.magaluIdentity;
  const account=await accountRepository.findAccountByIdForTenant(accountId,identity.dachTenantId);
  if(!account){const e=new Error("Conta Magalu não encontrada para esta empresa.");e.status=404;e.code="MAGALU_ACCOUNT_NOT_FOUND";throw e;}
  if(String(account.status)!=="active"){const e=new Error("A conta Magalu não está ativa.");e.status=409;e.code="MAGALU_ACCOUNT_INACTIVE";throw e;}
  const access=await checkAccountAccess(identity,account,{action:write?"WRITE magalu":"READ magalu",force});
  if(!access.allow){const e=new Error("O Hub não confirmou acesso a esta conta Magalu.");e.status=403;e.code=write?"MAGALU_SKU_HUB_WRITE_DENIED":"MAGALU_SKU_HUB_ACCESS_DENIED";throw e;}
  if(write&&!hasWriteScope(account.scopes)){const e=new Error(`Scope ausente: ${WRITE_SCOPE}. Reconecte a conta após liberar esse escopo no client Magalu.`);e.status=409;e.code="MAGALU_SKU_WRITE_SCOPE_MISSING";throw e;}
  return account;
}
async function status(req,res,next){try{const accountId=int(req.query?.account_id);let account=null;if(accountId)account=await accountFor(req);return res.json({ok:true,enabled:env.MAGALU_SKU_WRITE_ENABLED,scope:WRITE_SCOPE,max_batch_size:env.MAGALU_SKU_MAX_BATCH_SIZE,preview_ttl_seconds:env.MAGALU_SKU_PREVIEW_TTL_SECONDS,concurrency:env.MAGALU_SKU_UPDATE_CONCURRENCY,rate_limit_per_minute:env.MAGALU_RATE_LIMIT_SKU_WRITE_PER_MINUTE,account:account?{id:account.id,status:account.status,has_write_scope:hasWriteScope(account.scopes)}:null});}catch(error){return fail(res,error,"Não foi possível carregar o status da Gestão de SKUs.");}}
async function list(req,res){try{const account=await accountFor(req);const data=await skuMassRepository.listSkus(account.id,{q:req.query?.q,status:req.query?.status,active:req.query?.active,page:req.query?.page,limit:req.query?.limit});return res.json({ok:true,...data,account:{id:account.id,magalu_tenant_id:account.magalu_tenant_id,name:account.magalu_tenant_name||null}});}catch(error){return fail(res,error,"Não foi possível listar os SKUs.");}}
async function validationInfo(req,res){try{const account=await accountFor(req);const sku=text(req.params.sku,64);if(!sku)return res.status(400).json({ok:false,error:"invalid_sku"});const response=await remote.validationInfo(account,sku);return res.json({ok:true,sku,status:response.status,request_id:response.requestId||null,data:response.data||null});}catch(error){return fail(res,error,"Não foi possível consultar validation-info.");}}
async function preview(req,res){try{const account=await accountFor(req,{write:true,force:true});const identity=req.magaluIdentity;const preview=await skuMassRepository.createPreview({accountId:account.id,dachTenantId:identity.dachTenantId,dachUserId:identity.dachUserId,action:req.body?.action,selection:req.body?.selection||{}});await appendAuditEvent({accountId:account.id,dachTenantId:identity.dachTenantId,dachUserId:identity.dachUserId,magaluTenantId:account.magalu_tenant_id,action:"SKU_MASS_PREVIEW_CREATED",category:"write",outcome:"success",resourceType:"sku",batchId:preview.id,source:"sku-management",details:{action:preview.action,selection_mode:preview.selection_mode,selected_count:preview.selected_count,change_count:preview.change_count}}).catch(()=>{});return res.json({ok:true,preview:{id:preview.id,action:preview.action,selection_mode:preview.selection_mode,selected_count:preview.selected_count,change_count:preview.change_count,rows:preview.rows,created_at:preview.created_at,expires_at:preview.expires_at},write_enabled:env.MAGALU_SKU_WRITE_ENABLED});}catch(error){return fail(res,error,"Não foi possível gerar o preview massivo.");}}
async function apply(req,res){try{if(!env.MAGALU_SKU_WRITE_ENABLED)return res.status(409).json({ok:false,error:"MAGALU_SKU_WRITE_DISABLED",message:"MAGALU_SKU_WRITE_ENABLED=false. O preview é permitido, mas nenhuma escrita será enfileirada."});const identity=req.magaluIdentity;const preview=await skuMassRepository.getPreview(req.body?.preview_id,{dachTenantId:identity.dachTenantId,dachUserId:identity.dachUserId});if(!preview)return res.status(404).json({ok:false,error:"MAGALU_SKU_PREVIEW_NOT_FOUND"});await accountFor(req,{write:true,force:true,accountIdOverride:preview.account_id});const created=await skuMassRepository.createBatchFromPreview(preview.id,{dachTenantId:identity.dachTenantId,dachUserId:identity.dachUserId});const jobs=await enqueueSkuMassItems(created.items);await appendAuditEvent({accountId:preview.account_id,dachTenantId:identity.dachTenantId,dachUserId:identity.dachUserId,action:"SKU_MASS_BATCH_QUEUED",category:"write",outcome:"success",resourceType:"sku",batchId:created.batchId,source:"sku-management",details:{action:preview.action,total:created.items.length,jobs:jobs.length}}).catch(()=>{});return res.status(202).json({ok:true,batch_id:created.batchId,total:created.items.length,queued:jobs.length});}catch(error){return fail(res,error,"Não foi possível criar o lote massivo.");}}
async function batches(req,res){try{await accountFor(req);const data=await skuMassRepository.listBatches(req.magaluIdentity.dachTenantId,{accountId:req.query?.account_id,status:req.query?.status,page:req.query?.page,limit:req.query?.limit});return res.json({ok:true,...data});}catch(error){return fail(res,error,"Não foi possível listar os lotes.");}}
async function batch(req,res){try{const data=await skuMassRepository.batchDetail(req.params.batchId,req.magaluIdentity.dachTenantId);if(!data)return res.status(404).json({ok:false,error:"MAGALU_SKU_BATCH_NOT_FOUND"});return res.json({ok:true,...data});}catch(error){return fail(res,error,"Não foi possível abrir o lote.");}}
async function reverify(req,res){try{const identity=req.magaluIdentity;const item=await skuMassRepository.getItemForTenant(req.params.itemId,identity.dachTenantId);if(!item)return res.status(404).json({ok:false,error:"MAGALU_SKU_ITEM_NOT_FOUND"});if(!["uncertain","divergent"].includes(String(item.status)))return res.status(409).json({ok:false,error:"MAGALU_SKU_REVERIFY_INVALID_STATE",message:"Somente itens uncertain/divergent podem ser reverificados."});await accountFor(req,{write:false,force:true,accountIdOverride:item.account_id});const jobs=await enqueueSkuMassReverify(item);await appendAuditEvent({accountId:item.account_id,dachTenantId:item.dach_tenant_id,dachUserId:identity.dachUserId,action:"SKU_MASS_REVERIFY_REQUESTED",category:"write",outcome:"info",resourceType:"sku",sku:item.sku,batchId:item.batch_id,requestId:item.request_id||null,source:"sku-management",details:{item_id:item.id,previous_status:item.status,mode:"verification_only"}}).catch(()=>{});return res.status(202).json({ok:true,item_id:item.id,batch_id:item.batch_id,queued:jobs.length,mode:"verification_only"});}catch(error){return fail(res,error,"Não foi possível reverificar o item.");}}
module.exports={status,list,validationInfo,preview,apply,batches,batch,reverify,_test:{int,text}};
