"use strict";
const express=require("express");
const {authenticate,requirePasswordChangeComplete,requireCsrf}=require("../auth");
const {requirePermission}=require("../permissions");
const {withTenant,withPlatformAdmin}=require("../db");
const {audit}=require("../audit");
const router=express.Router();router.use(authenticate,requirePasswordChangeComplete);
router.get("/",requirePermission("commissions.read"),async(req,res,next)=>{try{
  let rows;
  if(req.vpAuth.isPlatformAdmin&&!req.vpAuth.tenantId){
    rows=await withPlatformAdmin(req.vpAuth.userId,async(client)=>(await client.query("SELECT * FROM volt_price.commission_references ORDER BY marketplace,category,valid_from DESC NULLS LAST")).rows);
  }else{
    rows=await withTenant(req.vpAuth.tenantId,req.vpAuth.userId,async(client)=>(await client.query("SELECT * FROM volt_price.commission_references WHERE tenant_id IS NULL OR tenant_id=$1 ORDER BY marketplace,category,valid_from DESC NULLS LAST",[req.vpAuth.tenantId])).rows);
  }
  res.json({commissions:rows});
}catch(e){next(e);}});
router.post("/",requireCsrf,requirePermission("commissions.manage"),async(req,res,next)=>{try{const b=req.body||{};const runner=req.vpAuth.isPlatformAdmin&&b.global?withPlatformAdmin:withTenant;const args=req.vpAuth.isPlatformAdmin&&b.global?[req.vpAuth.userId]:[req.vpAuth.tenantId,req.vpAuth.userId];const row=await runner(...args,async(client)=>{const tenantId=req.vpAuth.isPlatformAdmin&&b.global?null:req.vpAuth.tenantId;const r=(await client.query(`INSERT INTO volt_price.commission_references (tenant_id,marketplace,category,title,commission_percent_min,commission_percent_max,fixed_fee,extra_fees,notes,source_url,source_type,valid_from,valid_to,last_verified_at,status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10,$11,$12,$13,$14,$15) RETURNING *`,[tenantId,b.marketplace,b.category||null,b.title,b.commissionPercentMin||null,b.commissionPercentMax||null,b.fixedFee||null,JSON.stringify(b.extraFees||[]),b.notes||null,b.sourceUrl||null,b.sourceType||"MANUAL",b.validFrom||null,b.validTo||null,b.lastVerifiedAt||null,b.status||"current"])).rows[0];await audit(client,{tenantId,actorUserId:req.vpAuth.userId,actorType:req.vpAuth.isPlatformAdmin?"platform_admin":"user",action:"commission.create",resourceType:"commission_reference",resourceId:r.id,metadata:{marketplace:b.marketplace}});return r;});res.status(201).json({commission:row});}catch(e){next(e);}});
router.patch("/:id",requireCsrf,requirePermission("commissions.manage"),async(req,res,next)=>{try{const b=req.body||{};const runner=req.vpAuth.isPlatformAdmin?withPlatformAdmin:withTenant;const args=req.vpAuth.isPlatformAdmin?[req.vpAuth.userId]:[req.vpAuth.tenantId,req.vpAuth.userId];const row=await runner(...args,async(client)=>{const existing=(await client.query("SELECT * FROM volt_price.commission_references WHERE id=$1",[req.params.id])).rows[0];if(!existing)throw Object.assign(new Error("Referencia nao encontrada."),{statusCode:404});if(!req.vpAuth.isPlatformAdmin&&existing.tenant_id!==req.vpAuth.tenantId)throw Object.assign(new Error("Referencia global so pode ser alterada pelo Admin Master."),{statusCode:403});const merged={...existing,...b};const r=(await client.query(`UPDATE volt_price.commission_references SET category=$2,title=$3,commission_percent_min=$4,commission_percent_max=$5,fixed_fee=$6,extra_fees=$7::jsonb,notes=$8,source_url=$9,source_type=$10,valid_from=$11,valid_to=$12,last_verified_at=$13,status=$14,updated_at=now() WHERE id=$1 RETURNING *`,[req.params.id,merged.category,merged.title,merged.commissionPercentMin??merged.commission_percent_min,merged.commissionPercentMax??merged.commission_percent_max,merged.fixedFee??merged.fixed_fee,JSON.stringify(merged.extraFees??merged.extra_fees??[]),merged.notes,merged.sourceUrl??merged.source_url,merged.sourceType??merged.source_type,merged.validFrom??merged.valid_from,merged.validTo??merged.valid_to,merged.lastVerifiedAt??merged.last_verified_at,merged.status])).rows[0];await audit(client,{tenantId:existing.tenant_id,actorUserId:req.vpAuth.userId,actorType:req.vpAuth.isPlatformAdmin?"platform_admin":"user",action:"commission.update",resourceType:"commission_reference",resourceId:r.id,metadata:{before:existing,after:r}});return r;});res.json({commission:row});}catch(e){next(e);}});
module.exports={commissionsRouter:router};
