"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const path=require("node:path");
const root=path.resolve(__dirname,"..");const read=(p)=>fs.readFileSync(path.join(root,p),"utf8");
test("migration 006 creates Audit V2 and retention structures",()=>{const s=read("db/migrations/006_audit_v2_retention.sql");for(const token of ["event_key","audit_retention_rules","audit_maintenance_runs","retention_days","max_days"])assert.match(s,new RegExp(token));assert.match(s,/between 1 and 90/i);});
test("master exposes audit exports and protected retention mutations",()=>{const r=read("src/routes/master.routes.js");assert.match(r,/audit\/events\/export\.xlsx/);assert.match(r,/retention\/dry-run/);assert.match(r,/requireMagaluMasterDestructive, masterController\.retentionUpdate/);assert.match(r,/requireMagaluMasterDestructive, masterController\.retentionCleanup/);});
test("worker installs daily audit maintenance queue",()=>{const q=read("src/config/queueNames.js");const w=read("src/worker.js");const mq=read("src/queues/magaluQueue.js");assert.match(q,/magalu-audit-maintenance/);assert.match(w,/startAuditMaintenanceWorker/);assert.match(mq,/17 3 \* \* \*/);assert.match(mq,/America\/Sao_Paulo/);});
test("browser never connects directly to Redis",()=>{const js=read("public/js/magalu-master-audit.js");assert.doesNotMatch(js,/ioredis|redis:\/\/|new Redis/i);assert.match(js,/\/magalu\/api\/master/);});
test("audit pipeline centralizes sanitization",()=>{assert.match(read("src/repositories/writeRepository.js"),/appendAuditEvent/);assert.match(read("src/repositories/accountManagementRepository.js"),/appendAuditEvent/);assert.match(read("src/repositories/auditRepository.js"),/normalizeAuditEvent/);});
test("retention limits match project policy",()=>{const s=read("db/migrations/006_audit_v2_retention.sql");assert.match(s,/\('default'.*30, 15, 30/);assert.match(s,/\('failure'.*60, 30, 60/);assert.match(s,/\('admin'.*90, 90, 90/);assert.match(s,/\('uncertain'.*90, 90, 90/);assert.match(s,/\('divergent'.*90, 90, 90/);});

test("retention precedence keeps admin/critical/ambiguous events at 90 days",()=>{const s=read("src/services/auditRetentionService.js");assert.match(s,/order by r\.priority desc/);});
test("no token ciphertext or client secret is rendered by Master audit UI",()=>{for(const f of ["public/js/magalu-master-audit.js","views/master.html","src/services/auditRetentionService.js"])assert.doesNotMatch(read(f),/access_token_ciphertext|refresh_token_ciphertext|client_secret|secret_ciphertext/i);});
