"use strict";
process.env.MAGALU_ENCRYPTION_KEY = Buffer.alloc(32, 11).toString("base64");
process.env.MAGALU_OAUTH_CLIENT_ID = "client-hardening";
process.env.MAGALU_OAUTH_CLIENT_SECRET = "secret-hardening";
process.env.MAGALU_OAUTH_REDIRECT_URI = "https://dachbyte.tech/magalu/auth/callback";
const test=require("node:test");const assert=require("node:assert/strict");const Module=require("node:module");
function clearModule(relative){try{delete require.cache[require.resolve(relative)];}catch(_){}}
async function withLoadStubs(stubs,load,run){const original=Module._load;Module._load=function(request,parent,isMain){if(Object.prototype.hasOwnProperty.call(stubs,request))return stubs[request];return original.call(this,request,parent,isMain);};try{return await run(load());}finally{Module._load=original;}}
test("Hub access uses canonical ACCESS magalu audit action",()=>{clearModule("../src/services/hubAccessService");const hub=require("../src/services/hubAccessService");assert.equal(hub._test.DEFAULT_ACTION,"ACCESS magalu");assert.match(hub._test.cacheKey({dachTenantId:"dach-a",dachUserId:"user-a"}),/:ACCESS magalu$/);});
test("OAuth callback revalidates same DACH identity and bypasses Hub cache",async()=>{let options=null,calls=0;const identity={dachTenantId:"dach-a",dachUserId:"user-a",email:"u@x.com",modules:new Set(["magalu"])};clearModule("../src/controllers/oauthController");await withLoadStubs({"../repositories/oauthStateRepository":{consumeState:async()=>null},"../repositories/accountRepository":{listAccountsForTenant:async()=>[],findAccountByIdForTenant:async()=>null},"../queues/magaluQueue":{enqueueTokenRefresh:async()=>null,enqueueCatalogSync:async()=>null},"../services/magaluTokenService":{refreshAccount:async()=>({})},"../services/hubAccessService":{checkHubAccess:async(_i,o)=>{calls++;options=o;return{allow:true};}},"../middlewares/suiteAuth":{readSuiteIdentity:()=>({ok:true,identity})},"../services/magaluOAuthService":{beginAuthorization:async()=>({}),finishAuthorization:async()=>({}),publicOAuthConfig:()=>({configured:true})}},()=>require("../src/controllers/oauthController"),async c=>{const got=await c._test.revalidateCallbackAccess({}, {dach_tenant_id:"dach-a",dach_user_id:"user-a"});assert.equal(got.dachTenantId,"dach-a");assert.equal(calls,1);assert.deepEqual(options,{force:true,action:"ACCESS magalu"});});});
test("OAuth callback refuses changed DACH identity before Hub",async()=>{let calls=0;clearModule("../src/controllers/oauthController");await withLoadStubs({"../repositories/oauthStateRepository":{},"../repositories/accountRepository":{},"../queues/magaluQueue":{},"../services/magaluTokenService":{},"../services/hubAccessService":{checkHubAccess:async()=>{calls++;return{allow:true};}},"../middlewares/suiteAuth":{readSuiteIdentity:()=>({ok:true,identity:{dachTenantId:"other",dachUserId:"user-a",email:"u@x.com",modules:new Set(["magalu"])}})},"../services/magaluOAuthService":{beginAuthorization:async()=>({}),finishAuthorization:async()=>({}),publicOAuthConfig:()=>({})}},()=>require("../src/controllers/oauthController"),async c=>{await assert.rejects(c._test.revalidateCallbackAccess({}, {dach_tenant_id:"dach-a",dach_user_id:"user-a"}),e=>e?.code==="MAGALU_OAUTH_IDENTITY_MISMATCH"&&e?.status===403);assert.equal(calls,0);});});
test("OAuth callback refuses Hub revocation before token exchange",async()=>{const identity={dachTenantId:"dach-a",dachUserId:"user-a",email:"u@x.com",modules:new Set(["magalu"])};clearModule("../src/controllers/oauthController");await withLoadStubs({"../repositories/oauthStateRepository":{},"../repositories/accountRepository":{},"../queues/magaluQueue":{},"../services/magaluTokenService":{},"../services/hubAccessService":{checkHubAccess:async()=>({allow:false})},"../middlewares/suiteAuth":{readSuiteIdentity:()=>({ok:true,identity})},"../services/magaluOAuthService":{beginAuthorization:async()=>({}),finishAuthorization:async()=>({}),publicOAuthConfig:()=>({})}},()=>require("../src/controllers/oauthController"),async c=>{await assert.rejects(c._test.revalidateCallbackAccess({}, {dach_tenant_id:"dach-a",dach_user_id:"user-a"}),e=>e?.code==="MAGALU_OAUTH_HUB_ACCESS_REVOKED"&&e?.status===403);});});
test("simultaneous cross-tenant ownership race converts 23505 into 409",async()=>{clearModule("../src/repositories/accountRepository");await withLoadStubs({"../config/postgres":{query:async()=>({rows:[]}),queryOne:async()=>null}},()=>require("../src/repositories/accountRepository"),async repo=>{const shared={row:null,initial:0,release:null};const barrier=new Promise(r=>{shared.release=r;});function client(name){let first=true;return{async query(sql,params=[]){const n=String(sql).replace(/\s+/g," ").trim().toLowerCase();if(n==="savepoint magalu_account_insert"||n==="release savepoint magalu_account_insert"||n==="rollback to savepoint magalu_account_insert")return{rows:[]};if(n.includes("from magalu.accounts")&&n.includes("where magalu_tenant_id = $1")&&n.includes("for update")){if(first){first=false;shared.initial++;if(shared.initial===2)shared.release();await barrier;return{rows:[]};}return{rows:shared.row?[shared.row]:[]};}if(n.startsWith("insert into magalu.accounts")){if(name==="b")await new Promise(r=>setTimeout(r,10));if(shared.row){const e=new Error("duplicate");e.code="23505";throw e;}shared.row={id:91,dach_tenant_id:params[0],magalu_tenant_id:params[2]};return{rows:[shared.row]};}if(n.startsWith("update magalu.accounts"))return{rows:[shared.row]};throw new Error(`Unexpected SQL: ${n}`);}};}const args=d=>({dachTenantId:d,dachUserId:`u-${d}`,magaluTenantId:"GENPUB.shared",scopes:["open:portfolio-skus-seller:read"],metadata:{}});const settled=await Promise.allSettled([repo.upsertConnectedAccount(client("a"),args("dach-a")),repo.upsertConnectedAccount(client("b"),args("dach-b"))]);assert.equal(settled.filter(x=>x.status==="fulfilled").length,1);const rejected=settled.find(x=>x.status==="rejected");assert.equal(rejected.reason.code,"MAGALU_TENANT_ALREADY_LINKED");assert.equal(rejected.reason.status,409);});});
