"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const path=require("node:path");
const root=path.resolve(__dirname,"..");const read=(p)=>fs.readFileSync(path.join(root,p),"utf8");

test("margem exclui pedidos sem custo do resultado conhecido",()=>{const c=read("src/repositories/uxAnalyticsRepository.js");assert.match(c,/case when missing_cost_items=0 then gmv-product_cost-taxes-operating_costs else null end as known_result/);assert.match(c,/sum\(known_result\) filter\(where cost_complete\)/);assert.match(c,/incomplete_gmv/);});
test("margem usa os mesmos filtros no resumo e nas linhas",()=>{const c=read("src/repositories/uxAnalyticsRepository.js");assert.match(c,/function marginFilters/);assert.match(c,/from base \$\{whereSql\}/);assert.match(c,/select code,known_result,gmv from base \$\{whereSql\}/);});
test("custos preservam campos omitidos e suportam todos componentes",()=>{const c=read("src/repositories/financialRepository.js");for(const token of ["tax_rate","packaging_cost","operational_cost","other_cost","notes","has(input"]){assert.ok(c.includes(token),token);}});
test("estoque analítico é paginado e pesquisável",()=>{const c=read("public/js/magalu-stock-price.js");assert.match(c,/mg-stock-analysis-search/);assert.match(c,/page=\$\{state\.page\}/);assert.match(c,/mg-stock-next/);});
test("renderer legado do painel foi removido",()=>{const c=read("public/js/magalu-app.js");assert.doesNotMatch(c,/renderCommercialDashboard\(|renderDashboard\(/);assert.match(c,/magalu:dashboarddata/);});
test("recorte de preço e estoque é carregado explicitamente e limitado pelo lote",()=>{const c=read("public/js/magalu-app.js");assert.match(c,/loadWriteFilterSelection/);assert.match(c,/mg-price-load-filter/);assert.match(c,/mg-stock-load-filter/);assert.match(c,/const rows = state\.writeRows\[resource\] \|\| \[\]/);});
test("valores de custo inválidos são rejeitados sem virar zero",()=>{const {suppliedNumber}=require("../src/repositories/financialRepository")._test;for(const value of ["",null,"-1","abc","Infinity"]){assert.throws(()=>suppliedNumber({unit_cost:value},"unit_cost",8),{status:422});}assert.equal(suppliedNumber({},"unit_cost",8),8);assert.equal(suppliedNumber({unit_cost:"0"},"unit_cost",8),0);assert.throws(()=>suppliedNumber({tax_rate:"101"},"tax_rate",5,{max:100}),{status:422});});
test("pedido sem itens sincronizados permanece incompleto",()=>{const c=read("src/repositories/uxAnalyticsRepository.js");assert.match(c,/case when coalesce\(ic\.synced_item_rows,0\)=0 then 1 else 0 end/);});
test("frontend continua independente do Seller ML",()=>{for(const p of ["public/js/magalu-financial.js","public/js/magalu-stock-price.js","public/css/magalu-post-review-fixes.css"]){const c=read(p);assert.doesNotMatch(c,/\/ml\/|seller-ml|ml-shell/i);}});
