"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const path=require("node:path");
const root=path.resolve(__dirname,"..");const read=p=>fs.readFileSync(path.join(root,p),"utf8");
const payload=require("../src/services/skuMassPayload");

test("migration 007 creates preview, batches and items with guarded states",()=>{const s=read("db/migrations/007_mass_sku_operations.sql");for(const t of ["sku_mass_previews","mass_operation_batches","mass_operation_items","dispatching","uncertain","divergent","canceled"])assert.match(s,new RegExp(t));assert.match(s,/selected_count.*5000/s);});
test("mass retention matches project policy",()=>{const s=read("src/repositories/skuMassRepository.js");assert.match(s,/status='succeeded'.*interval '30 days'/s);assert.match(s,/status in\('failed','stale','canceled'\).*interval '60 days'/s);assert.match(s,/status in\('uncertain','divergent'\).*interval '90 days'/s);assert.match(s,/b\.status='completed'.*interval '60 days'/s);assert.match(s,/b\.status in\('partial','failed','canceled'\).*interval '90 days'/s);});
test("SKU write is disabled by default and OAuth only requests scope when enabled",()=>{const s=read("src/config/env.js");assert.match(s,/MAGALU_SKU_WRITE_ENABLED = bool\(process\.env\.MAGALU_SKU_WRITE_ENABLED, false\)/);assert.match(s,/open:portfolio-skus-seller:write/);assert.match(s,/MAGALU_SKU_WRITE_ENABLED \? \[SKU_WRITE_SCOPE\] : \[\]/);});
test("queue and worker enforce concurrency 6 and internal 500 per minute",()=>{const q=read("src/config/queueNames.js"),w=read("src/jobs/skuUpdate.worker.js"),e=read("src/config/env.js");assert.match(q,/magalu-sku-update/);assert.match(e,/MAGALU_SKU_UPDATE_CONCURRENCY: 6/);assert.match(e,/MAGALU_RATE_LIMIT_SKU_WRITE_PER_MINUTE: Math\.min\(500/);assert.match(w,/concurrency:env\.MAGALU_SKU_UPDATE_CONCURRENCY/);assert.match(w,/limiter:\{max:env\.MAGALU_RATE_LIMIT_SKU_WRITE_PER_MINUTE,duration:60000\}/);});
test("execution keeps GET -> preview compare -> Hub force -> dispatch -> PATCH -> verification order",()=>{const s=read("src/services/skuMassExecutionService.js");const get=s.indexOf("beforeResponse=await remote.readSku");const compare=s.indexOf("samePreviewState",get);const hub=s.indexOf("force:true,action:\"WRITE magalu\"");const dispatch=s.indexOf("setDispatching");const patch=s.indexOf("remote.patchActive");const verify=s.lastIndexOf("verifyDesired(account,item)");assert.ok(get>0&&compare>get&&hub>compare&&dispatch>hub&&patch>dispatch&&verify>patch);});
test("post-dispatch ambiguous states reconcile by GET and never resend PATCH automatically",()=>{const s=read("src/services/skuMassExecutionService.js");assert.match(s,/RECONCILIATION_ONLY.*dispatching.*accepted.*divergent.*uncertain/);assert.match(s,/if\(isReconciliationOnly\(item\)\)return reconcile\(account,item\)/);assert.match(s,/Nenhum reenvio automático foi feito/);});
test("remote SKU contract uses PATCH active and validation-info",()=>{const s=read("src/services/skuRemoteService.js");assert.match(s,/\/validation-info/);assert.match(s,/method:\"PATCH\"/);assert.match(s,/body:\{ active:active === true \}/);assert.match(s,/attempts:1/);});
test("payload validates action, scope and remote preview state",()=>{assert.equal(payload.desiredActive("activate"),true);assert.equal(payload.desiredActive("deactivate"),false);assert.equal(payload.hasWriteScope([payload.WRITE_SCOPE]),true);assert.equal(payload.samePreviewState({active:true,status:"PUBLISHED"},{active:true,status:"PUBLISHED"}),true);assert.equal(payload.samePreviewState({active:true,status:"PUBLISHED"},{active:false,status:"PUBLISHED"}),false);assert.throws(()=>payload.normalizeAction("delete"));});
test("tenant UI exposes search, filters, select page/all and preview confirmation",()=>{const h=read("views/gestao-skus.html"),j=read("public/js/magalu-sku-management.js");assert.match(h,/\/magalu\/gestao-skus/);assert.match(h,/Selecionar todos os resultados do filtro/);assert.match(h,/Ativar/);assert.match(h,/Desativar/);assert.match(j,/mode:\"all_filtered\"/);assert.match(j,/\/preview/);assert.match(j,/\/apply/);assert.match(j,/validation-info/);assert.doesNotMatch(`${h}\n${j}`,/access_token|refresh_token|client_secret|secret_ciphertext/i);});
test("API preserves SKU management routes from stage 5 onward",()=>{const r=read("src/routes/api.routes.js"),i=read("src/routes/index.js");assert.match(r,/router\.use\("\/sku-management", skuManagementRoutes\)/);const stage=r.match(/stage:(\d+)/);assert.ok(Number(stage?.[1]||0)>=5);assert.match(i,/router\.get\("\/gestao-skus"/);});
test("Master connects mass batches and has verification-only action",()=>{const repo=read("src/repositories/masterRepository.js"),service=read("src/services/masterService.js"),routes=read("src/routes/master.routes.js"),ui=read("public/js/magalu-master.js");assert.match(repo,/listMassBatchesForMaster/);assert.match(repo,/source:\"mass_sku\"/);assert.match(service,/reverifyMassOperation/);assert.match(service,/enqueueSkuMassReverify/);assert.match(routes,/operations\/mass\/:itemId\/reverify/);assert.match(ui,/operations\/mass/);assert.doesNotMatch(`${service}\n${ui}`,/reprocessar tudo/i);});
test("unlink blocker recognizes the now-real mass schema",()=>{const s=read("src/repositories/accountManagementRepository.js");assert.match(s,/magalu\.mass_operation_items/);for(const state of ["queued","running","dispatching","accepted","divergent","uncertain"])assert.ok(s.includes(`"${state}"`));});
test("mass writes are auditable without secrets",()=>{const e=read("src/services/skuMassExecutionService.js"),c=read("src/controllers/skuManagementController.js");assert.match(e,/SKU_MASS_DISPATCHING/);assert.match(e,/SKU_MASS_ACCEPTED/);assert.match(c,/SKU_MASS_PREVIEW_CREATED/);assert.match(c,/SKU_MASS_BATCH_QUEUED/);assert.doesNotMatch(`${e}\n${c}`,/access_token|refresh_token|client_secret|secret_ciphertext/i);});
