"use strict";
const env=require("../config/env");
const accountRepository=require("../repositories/accountRepository");
const orderRepository=require("../repositories/orderRepository");
const repo=require("../repositories/deliveryWriteRepository");
const remote=require("./deliveryWriteRemoteService");
const {checkAccountAccess}=require("./hubResourceAccessService");
const {appendAuditEvent}=require("../repositories/auditRepository");
const {ACTIONS,requiredScopes,hasScopes,snapshot,sameSnapshot,invoiceKeyPresent,sanitizeRemote}=require("./deliveryWritePayload");
const RECON_ONLY=new Set(["dispatching","accepted","divergent","uncertain"]);
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function safe(v,max=1000){return String(v==null?"":v).trim().slice(0,max);}
function writeEnabled(action){return action===ACTIONS.INVOICE?env.MAGALU_INVOICE_WRITE_ENABLED===true:env.MAGALU_DELIVERY_WRITE_ENABLED===true;}
function isReconciliationOnly(op){return RECON_ONLY.has(String(op?.status||""))||Boolean(op?.remote_accepted_at);}
async function audit(op,eventKey,{outcome="success",severity="info",details={}}={}){return appendAuditEvent({action:eventKey,category:"write",severity,outcome,accountId:op.account_id,dachTenantId:op.dach_tenant_id,dachUserId:op.dach_user_id,magaluTenantId:op.magalu_tenant_id||null,resourceType:"delivery",batchId:`delivery:${op.id}`,requestId:op.request_id||op.idempotency_key||null,source:"delivery-write-worker",details:{operation_id:op.id,delivery_id:op.delivery_id,order_code:op.order_code,action:op.action,...details}}).catch(()=>null);}
async function finish(op,status,code,message,extra={}){const saved=await repo.finish(op.id,{status,afterPayload:extra.afterPayload||null,errorCode:code||null,errorMessage:message||null,responseStatus:extra.responseStatus||null,responsePayload:extra.responsePayload==null?null:sanitizeRemote(extra.responsePayload),requestId:extra.requestId||op.request_id||null});const outcome=status==="uncertain"?"uncertain":status==="divergent"?"divergent":status==="stale"?"stale":status==="succeeded"?"success":"failure";await audit({...op,...saved},`DELIVERY_WRITE_${status.toUpperCase()}`,{outcome,severity:["failed","uncertain","divergent"].includes(status)?"warning":"info",details:{code:code||null,message:message||null,response_status:extra.responseStatus||null}});return saved;}
async function verify(account,op){const attempts=Math.max(1,Number(env.MAGALU_DELIVERY_WRITE_VERIFY_ATTEMPTS||6)),delay=Math.max(250,Number(env.MAGALU_DELIVERY_WRITE_VERIFY_DELAY_MS||1500));let last=null;for(let i=1;i<=attempts;i+=1){if(i>1)await sleep(delay*Math.min(i,4));try{if(op.action===ACTIONS.FINISH){const response=await remote.getDelivery(account,op.delivery_id,op.channel_id);last=response;const current=snapshot(response.data||{},op.before_payload||{});if(current.status==="delivered"){await orderRepository.upsertDelivery(account.id,require("./orderPayload").normalizeDelivery(response.data||{}),{httpStatus:response.status||200}).catch(()=>{});return{verified:true,after:current,requestId:response.requestId||null};}}else{const response=await remote.getInvoices(account,op.delivery_id,op.channel_id);last=response;const key=op.requested_metadata?.key;if(invoiceKeyPresent(response.data,key))return{verified:true,after:{invoice_key:key,present:true},requestId:response.requestId||null};}}catch(error){last=error;}}return{verified:false,last};}
async function reconcile(account,op){const checked=await verify(account,op);if(checked.verified)return finish(op,"succeeded",null,null,{afterPayload:checked.after,requestId:checked.requestId});const accepted=op.status==="accepted"||op.status==="divergent"||Boolean(op.remote_accepted_at);return finish(op,accepted?"divergent":"uncertain",accepted?"MAGALU_DELIVERY_WRITE_NOT_CONVERGED":"MAGALU_DELIVERY_WRITE_RESULT_UNCERTAIN",accepted?"A operação foi aceita, mas o estado remoto ainda não convergiu.":"Não é seguro afirmar se a requisição chegou à Magalu. Nenhum POST foi reenviado automaticamente.");}
async function execute(id){let op=await repo.getOperation(id);if(!op)throw new Error(`Operação de entrega inexistente: ${id}`);if(["succeeded","stale","failed","canceled"].includes(String(op.status)))return repo.publicOperation(op);if(op.status==="queued")op=await repo.claim(op.id)||op;if(!["running","dispatching","accepted","divergent","uncertain"].includes(String(op.status)))return repo.publicOperation(op);
 const account=await accountRepository.findAccountById(op.account_id);if(!account||String(account.dach_tenant_id)!==String(op.dach_tenant_id))return finish(op,"failed","MAGALU_DELIVERY_ACCOUNT_MISMATCH","Conta/tenant não correspondem à operação.");op.magalu_tenant_id=account.magalu_tenant_id;if(isReconciliationOnly(op))return reconcile(account,op);if(String(account.status)!=="active")return finish(op,"failed","MAGALU_DELIVERY_ACCOUNT_INACTIVE","A conta Magalu não está ativa.");if(!writeEnabled(op.action))return finish(op,"failed","MAGALU_DELIVERY_WRITE_DISABLED","A escrita remota desta ação está desabilitada por configuração.");if(!hasScopes(account,requiredScopes(op.action)))return finish(op,"failed","MAGALU_DELIVERY_WRITE_SCOPE_MISSING","A conta não possui todos os scopes necessários para esta ação.");
 let before;try{before=await remote.getDelivery(account,op.delivery_id,op.channel_id);}catch(error){return finish(op,Number(error?.status)===404?"stale":"failed",error?.code||`MAGALU_DELIVERY_GET_${Number(error?.status)||"ERROR"}`,error?.message||String(error),{responseStatus:Number(error?.status)||null,responsePayload:error?.payload||null,requestId:error?.requestId||null});}const current=snapshot(before.data||{},op.before_payload||{});if(!sameSnapshot(op.before_payload,current))return finish(op,"stale","MAGALU_DELIVERY_REMOTE_STATE_CHANGED","A entrega mudou desde o preview. Gere um novo preview antes de escrever.",{afterPayload:current,requestId:before.requestId||null});
 if(op.action===ACTIONS.INVOICE&&op.before_payload?.status!=="approved")return finish(op,"stale","MAGALU_INVOICE_STATUS_CHANGED","A NF-e só é enviada por este fluxo quando a entrega permanece approved.",{afterPayload:current});if(op.action===ACTIONS.FINISH&&op.before_payload?.status!=="shipped")return finish(op,"stale","MAGALU_FINISH_STATUS_CHANGED","A finalização exige entrega em status shipped.",{afterPayload:current});
 if(op.action===ACTIONS.INVOICE){try{const existing=await remote.getInvoices(account,op.delivery_id,op.channel_id);if(invoiceKeyPresent(existing.data,op.requested_metadata?.key))return finish(op,"succeeded",null,null,{afterPayload:{invoice_key:op.requested_metadata?.key,present:true},requestId:existing.requestId||null});}catch(_e){}}
 const hub=await checkAccountAccess({dachTenantId:op.dach_tenant_id,dachUserId:op.dach_user_id},account,{force:true,action:"WRITE magalu"});if(!hub.allow)return finish(op,"failed","MAGALU_DELIVERY_HUB_WRITE_DENIED","O Hub não confirmou WRITE magalu imediatamente antes da chamada remota.",{responsePayload:{hub_reason:hub.reason||"hub_denied"}});
 const body=repo.decryptedBody(op);if(!body)return finish(op,"failed","MAGALU_DELIVERY_SENSITIVE_PAYLOAD_MISSING","O payload criptografado necessário para o primeiro envio não está disponível.");op=await repo.setDispatching(op.id,op.idempotency_key)||{...op,status:"dispatching",request_id:op.idempotency_key,sensitive_payload_ciphertext:null};await audit(op,"DELIVERY_WRITE_DISPATCHING",{details:{method:"POST",requested_metadata:op.requested_metadata}});let response;try{response=op.action===ACTIONS.INVOICE?await remote.sendInvoice(account,op.delivery_id,body,op.idempotency_key):await remote.finishDelivery(account,op.delivery_id,body,op.idempotency_key);}catch(error){const status=Number(error?.status)||null,explicit=status&&status>=400&&status<500&&status!==408;return finish(op,explicit?"failed":"uncertain",explicit?(error?.code||`MAGALU_DELIVERY_POST_${status}`):"MAGALU_DELIVERY_WRITE_RESULT_UNCERTAIN",safe(error?.message||error,1800),{responseStatus:status,responsePayload:error?.payload||null,requestId:error?.requestId||op.idempotency_key});}
 op=await repo.setAccepted(op.id,{responseStatus:response.status,responsePayload:sanitizeRemote(response.data),requestId:response.requestId||op.idempotency_key})||op;await audit(op,"DELIVERY_WRITE_ACCEPTED",{details:{response_status:response.status}});return reconcile(account,op);}
module.exports={execute,_test:{writeEnabled,isReconciliationOnly,verify,safe}};
