"use strict";

function clean(value,max=1000){return String(value??"").trim().slice(0,max);}
function price(value){const normalized=typeof value==="string"?value.trim().replace(/\./g,"").replace(",","."):value;const result=Number(normalized);if(!Number.isFinite(result)||result<0)throw Object.assign(new Error("Informe um preco valido."),{statusCode:400});return Math.round(result*100)/100;}
function boolean(value,defaultValue=true){if(typeof value==="boolean")return value;if(value===0||["false","0","no","nao"].includes(clean(value,10).toLowerCase()))return false;if(value===1||["true","1","yes","sim"].includes(clean(value,10).toLowerCase()))return true;return defaultValue;}
function attribute(item,...ids){const accepted=new Set(ids);return clean((item?.attributes||[]).find((entry)=>accepted.has(String(entry.id||entry.name||"").toUpperCase()))?.value_name,200)||null;}

function normalizeMeliListing(item={}){return {externalId:clean(item.id,200),title:clean(item.title,500),price:price(item.price),currency:clean(item.currency_id,10)||"BRL",available:Number(item.available_quantity||0)>0,url:clean(item.permalink,1000)||null,sellerId:item.seller?.id===undefined||item.seller?.id===null?null:String(item.seller.id),sellerName:clean(item.seller?.nickname,200)||null,gtin:attribute(item,"GTIN","EAN","UPC"),brand:attribute(item,"BRAND"),mpn:attribute(item,"MPN","PART_NUMBER","MODEL"),categoryId:clean(item.category_id,100)||null,payload:{listingType:clean(item.listing_type_id,80)||null,condition:clean(item.condition,80)||null}};}
function normalizeImportedListing(item={}){const externalId=clean(item.externalId||item.external_id,200);if(!externalId)throw Object.assign(new Error("Informe o identificador externo do listing."),{statusCode:400});const title=clean(item.title,500);if(!title)throw Object.assign(new Error("Titulo do listing e obrigatorio."),{statusCode:400});return {externalId,title,price:price(item.price??item.observedPrice),currency:clean(item.currency,10)||"BRL",available:boolean(item.available,true),url:clean(item.url,1000)||null,sellerId:clean(item.sellerId,200)||null,sellerName:clean(item.sellerName||item.competitor,200)||null,gtin:clean(item.gtin||item.ean,100)||null,brand:clean(item.brand,200)||null,mpn:clean(item.mpn,200)||null,categoryId:clean(item.categoryId,100)||null,payload:item.payload&&typeof item.payload==="object"?item.payload:{}};}

module.exports={normalizeMeliListing,normalizeImportedListing};
