"use strict";

const crypto=require("crypto");
const {withTenant}=require("../db");
const {audit}=require("../audit");
const {redactForStorage}=require("../redact");
const meli=require("../integrations/mercadoLivre");
const {matchListing,detectListingSignals,summarizeProductMarket,missingFromCompleteSnapshot}=require("./analytics");
const {normalizeImportedListing,normalizeMeliListing}=require("./normalization");

const CHANNELS=new Set(["meli","shopee","amazon","magalu","casas_bahia","carrefour","other","import"]);
function clean(value,max=500){return String(value??"").trim().slice(0,max);}
function invalid(message){throw Object.assign(new Error(message),{statusCode:400});}
async function log(client,auth,request,action,type,id,metadata={}){await audit(client,{tenantId:auth.tenantId,actorUserId:auth.userId,action,resourceType:type,resourceId:String(id||""),metadata:redactForStorage(metadata),ip:request?.ip,userAgent:request?.get?.("user-agent")});}
async function visible(client,table,id,label){const allowed=new Set(["integration_connections","market_sources","competitor_listings","market_matches","products","market_signals"]);if(!allowed.has(table))throw new Error("Tabela de validacao invalida.");const row=(await client.query(`SELECT * FROM volt_price.${table} WHERE id=$1`,[id])).rows[0];if(!row)throw Object.assign(new Error(`${label} nao encontrado neste tenant.`),{statusCode:404});return row;}
function fingerprint(listing){return crypto.createHash("sha256").update(JSON.stringify([listing.price,listing.available,listing.currency,listing.title,listing.sellerId,listing.gtin,listing.brand,listing.mpn])).digest("hex");}

async function marketOverview(auth,query={}){return withTenant(auth.tenantId,auth.userId,async(client)=>{const from=clean(query.from,10)||new Date(Date.now()-30*86400000).toISOString().slice(0,10);const to=clean(query.to,10)||new Date().toISOString().slice(0,10);
  const [sources,listings,matches,signals,history,products]=await Promise.all([
    client.query("SELECT * FROM volt_price.market_sources ORDER BY channel,name"),
    client.query(`SELECT l.*,s.channel,s.name source_name,m.id match_id,m.product_id,m.status match_status,m.confidence,m.reason,p.sku,p.name product_name,p.metadata product_metadata FROM volt_price.competitor_listings l JOIN volt_price.market_sources s ON s.id=l.source_id LEFT JOIN volt_price.market_matches m ON m.listing_id=l.id LEFT JOIN volt_price.products p ON p.id=m.product_id ORDER BY l.last_seen_at DESC LIMIT 1500`),
    client.query(`SELECT m.*,l.title listing_title,l.external_listing_id,s.channel,s.name source_name,p.sku,p.name product_name FROM volt_price.market_matches m JOIN volt_price.competitor_listings l ON l.id=m.listing_id JOIN volt_price.market_sources s ON s.id=l.source_id LEFT JOIN volt_price.products p ON p.id=m.product_id WHERE m.status IN ('review','unmatched') ORDER BY m.confidence DESC,m.updated_at DESC LIMIT 500`),
    client.query(`SELECT g.*,l.title listing_title,p.sku,p.name product_name,s.channel FROM volt_price.market_signals g LEFT JOIN volt_price.competitor_listings l ON l.id=g.listing_id LEFT JOIN volt_price.products p ON p.id=g.product_id LEFT JOIN volt_price.market_sources s ON s.id=g.source_id WHERE g.observed_at::date BETWEEN $1::date AND $2::date ORDER BY CASE g.severity WHEN 'critical' THEN 1 WHEN 'warning' THEN 2 WHEN 'opportunity' THEN 3 ELSE 4 END,g.observed_at DESC LIMIT 500`,[from,to]),
    client.query(`SELECT o.*,l.title listing_title,p.sku,p.name product_name FROM volt_price.market_observations o LEFT JOIN volt_price.competitor_listings l ON l.id=o.listing_id LEFT JOIN volt_price.products p ON p.id=o.product_id WHERE o.observed_at::date BETWEEN $1::date AND $2::date ORDER BY o.observed_at DESC LIMIT 2000`,[from,to]),
    client.query("SELECT p.id,p.sku,p.name,p.metadata,d.current_price FROM volt_price.products p LEFT JOIN LATERAL (SELECT current_price FROM volt_price.pricing_decisions WHERE product_id=p.id AND current_price IS NOT NULL ORDER BY created_at DESC LIMIT 1) d ON true ORDER BY p.name LIMIT 2000"),
  ]);
  const byProduct=products.rows.map((product)=>{const related=listings.rows.filter((listing)=>listing.product_id===product.id&&listing.match_status==="matched");const ownPrice=product.current_price??product.metadata?.currentPrice??product.metadata?.current_price??null;return {productId:product.id,sku:product.sku,name:product.name,ownPrice, ...summarizeProductMarket(related.map((row)=>({observed_price:row.current_price,available:row.available})),ownPrice)};}).filter((row)=>row.availableCompetitors||row.outOfStock);
  const summary={sources:sources.rowCount,listings:listings.rowCount,matched:listings.rows.filter((row)=>row.match_status==="matched").length,review:matches.rows.filter((row)=>row.status==="review").length,outOfStock:listings.rows.filter((row)=>!row.available).length,openSignals:signals.rows.filter((row)=>row.status==="open").length};
  return {period:{from,to},summary,sources:sources.rows,listings:listings.rows,matches:matches.rows,signals:signals.rows,history:history.rows,products:products.rows,byProduct};
});}

async function upsertSource(auth,input={},request=null){const channel=clean(input.channel,40);if(!CHANNELS.has(channel))invalid("Canal de concorrencia invalido.");const name=clean(input.name,200);const sourceKey=clean(input.sourceKey,200);if(!name||!sourceKey)invalid("Nome e sourceKey sao obrigatorios.");const kind=clean(input.sourceKind,30)||"import";if(!["official_api","import","manual"].includes(kind))invalid("Tipo de fonte invalido.");if(kind==="official_api"&&channel!=="meli")invalid("Nesta sprint, sincronizacao oficial automatica esta disponivel para Mercado Livre; use importacao para os demais canais.");
  return withTenant(auth.tenantId,auth.userId,async(client)=>{if(input.connectionId)await visible(client,"integration_connections",input.connectionId,"Conexao");const row=(await client.query(`INSERT INTO volt_price.market_sources(tenant_id,channel,source_kind,connection_id,source_key,name,external_seller_id,external_seller_name,site_id,status,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb) ON CONFLICT(tenant_id,source_key) DO UPDATE SET channel=EXCLUDED.channel,source_kind=EXCLUDED.source_kind,connection_id=EXCLUDED.connection_id,name=EXCLUDED.name,external_seller_id=EXCLUDED.external_seller_id,external_seller_name=EXCLUDED.external_seller_name,site_id=EXCLUDED.site_id,status=EXCLUDED.status,metadata=volt_price.market_sources.metadata||EXCLUDED.metadata,updated_at=now() RETURNING *`,[auth.tenantId,channel,kind,input.connectionId||null,sourceKey,name,clean(input.externalSellerId,200)||null,clean(input.externalSellerName,200)||null,clean(input.siteId,20)||null,clean(input.status,30)||"active",JSON.stringify(redactForStorage(input.metadata||{}))])).rows[0];await log(client,auth,request,"market.source.upsert","market_source",row.id,{channel,sourceKey,kind});return row;});}

async function importListings(auth,sourceId,items=[],options={},request=null){if(!Array.isArray(items)||(!items.length&&!options.fullSnapshot))invalid("Informe ao menos um listing.");if(items.length>1000)invalid("Importacao limitada a 1000 listings por chamada.");const observedAt=options.observedAt?new Date(options.observedAt):new Date();if(Number.isNaN(observedAt.getTime()))invalid("Data de observacao invalida.");
  return withTenant(auth.tenantId,auth.userId,async(client)=>{const source=await visible(client,"market_sources",sourceId,"Fonte");const products=(await client.query("SELECT p.id,p.sku,p.name,p.metadata,d.current_price FROM volt_price.products p LEFT JOIN LATERAL (SELECT current_price FROM volt_price.pricing_decisions WHERE product_id=p.id AND current_price IS NOT NULL ORDER BY created_at DESC LIMIT 1) d ON true")).rows;const output=[];
    for(const raw of items){const item=options.normalized?raw:normalizeImportedListing(raw);const previous=(await client.query("SELECT * FROM volt_price.competitor_listings WHERE source_id=$1 AND external_listing_id=$2 FOR UPDATE",[source.id,item.externalId])).rows[0]||null;
      const listing=(await client.query(`INSERT INTO volt_price.competitor_listings(tenant_id,source_id,external_listing_id,title,seller_id,seller_name,gtin,brand,mpn,category_id,listing_url,currency,current_price,available,first_seen_at,last_seen_at,payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$15,$16::jsonb) ON CONFLICT(tenant_id,source_id,external_listing_id) DO UPDATE SET title=EXCLUDED.title,seller_id=EXCLUDED.seller_id,seller_name=EXCLUDED.seller_name,gtin=coalesce(EXCLUDED.gtin,volt_price.competitor_listings.gtin),brand=coalesce(EXCLUDED.brand,volt_price.competitor_listings.brand),mpn=coalesce(EXCLUDED.mpn,volt_price.competitor_listings.mpn),category_id=coalesce(EXCLUDED.category_id,volt_price.competitor_listings.category_id),listing_url=coalesce(EXCLUDED.listing_url,volt_price.competitor_listings.listing_url),currency=EXCLUDED.currency,current_price=EXCLUDED.current_price,available=EXCLUDED.available,last_seen_at=EXCLUDED.last_seen_at,payload=volt_price.competitor_listings.payload||EXCLUDED.payload,updated_at=now() RETURNING *`,[auth.tenantId,source.id,item.externalId,item.title,item.sellerId,item.sellerName,item.gtin,item.brand,item.mpn,item.categoryId,item.url,item.currency,item.price,item.available,observedAt,JSON.stringify(redactForStorage(item.payload||{}))])).rows[0];
      let match=(await client.query("SELECT * FROM volt_price.market_matches WHERE listing_id=$1 FOR UPDATE",[listing.id])).rows[0]||null;
      if(!match?.reviewed_at){const suggestion=matchListing(item,products);match=(await client.query(`INSERT INTO volt_price.market_matches(tenant_id,listing_id,product_id,status,confidence,reason,evidence) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb) ON CONFLICT(tenant_id,listing_id) DO UPDATE SET product_id=EXCLUDED.product_id,status=EXCLUDED.status,confidence=EXCLUDED.confidence,reason=EXCLUDED.reason,evidence=EXCLUDED.evidence,updated_at=now() RETURNING *`,[auth.tenantId,listing.id,suggestion.productId,suggestion.status,suggestion.confidence,suggestion.reason,JSON.stringify({gtin:item.gtin,brand:item.brand,mpn:item.mpn,title:item.title})])).rows[0];}
      const ref=clean(raw.sourceRef,300)||`${source.id}:${item.externalId}:${observedAt.toISOString().slice(0,10)}`;const hash=fingerprint(item);let observation=(await client.query("SELECT * FROM volt_price.market_observations WHERE source_ref=$1 AND fingerprint=$2 AND is_current LIMIT 1",[ref,hash])).rows[0]||null;let unchanged=Boolean(observation);
      if(!observation){const current=(await client.query("SELECT * FROM volt_price.market_observations WHERE source_ref=$1 AND is_current FOR UPDATE",[ref])).rows[0]||null;if(current)await client.query("UPDATE volt_price.market_observations SET is_current=false,updated_at=now() WHERE id=$1",[current.id]);observation=(await client.query(`INSERT INTO volt_price.market_observations(tenant_id,product_id,source_id,listing_id,match_id,channel,competitor,external_listing_id,observed_price,currency,available,source_type,source_ref,fingerprint,version,is_current,payload,observed_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,true,$16::jsonb,$17) RETURNING *`,[auth.tenantId,match?.status==="matched"?match.product_id:null,source.id,listing.id,match?.id||null,source.channel,item.sellerName||source.name,item.externalId,item.price,item.currency,item.available,options.sourceType||"IMPORT",ref,hash,Number(current?.version||0)+1,JSON.stringify(redactForStorage(item.payload||{})),observedAt])).rows[0];}
      const detected=detectListingSignals(previous?{available:previous.available,price:previous.current_price}:null,{available:item.available,price:item.price});if(match?.status==="review")detected.push({type:"match_review",severity:"warning"});
      for(const signal of detected){const key=`${listing.id}:${signal.type}:${observedAt.toISOString().slice(0,10)}`;await client.query(`INSERT INTO volt_price.market_signals(tenant_id,source_id,listing_id,product_id,source_observation_id,signal_type,severity,dedupe_key,observed_at,value,evidence) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb) ON CONFLICT(tenant_id,dedupe_key) DO UPDATE SET source_observation_id=EXCLUDED.source_observation_id,value=EXCLUDED.value,evidence=EXCLUDED.evidence,updated_at=now()`,[auth.tenantId,source.id,listing.id,match?.status==="matched"?match.product_id:null,observation.id,signal.type,signal.severity,key,observedAt,signal.change??null,JSON.stringify({before:previous?{price:previous.current_price,available:previous.available}:null,after:{price:item.price,available:item.available}})]);}
      output.push({listing,match,observation,signals:detected,unchanged});
    }
    if(options.fullSnapshot){const seen=items.map((item)=>item.externalId||item.external_id).filter(Boolean);const existing=(await client.query("SELECT l.*,m.id match_id,m.product_id,m.status match_status FROM volt_price.competitor_listings l LEFT JOIN volt_price.market_matches m ON m.listing_id=l.id WHERE l.source_id=$1 FOR UPDATE OF l",[source.id])).rows;const missing=missingFromCompleteSnapshot(existing,seen,true);for(const listing of missing){await client.query("UPDATE volt_price.competitor_listings SET available=false,updated_at=now() WHERE id=$1",[listing.id]);const ref=`${source.id}:${listing.external_listing_id}:${observedAt.toISOString().slice(0,10)}`;const hash=fingerprint({price:Number(listing.current_price),available:false,currency:listing.currency,title:listing.title,sellerId:listing.seller_id,gtin:listing.gtin,brand:listing.brand,mpn:listing.mpn});const current=(await client.query("SELECT * FROM volt_price.market_observations WHERE source_ref=$1 AND is_current FOR UPDATE",[ref])).rows[0]||null;let observation=current;if(!current||current.fingerprint!==hash){if(current)await client.query("UPDATE volt_price.market_observations SET is_current=false,updated_at=now() WHERE id=$1",[current.id]);observation=(await client.query(`INSERT INTO volt_price.market_observations(tenant_id,product_id,source_id,listing_id,match_id,channel,competitor,external_listing_id,observed_price,currency,available,source_type,source_ref,fingerprint,version,is_current,payload,observed_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,false,'API',$11,$12,$13,true,'{}'::jsonb,$14) RETURNING *`,[auth.tenantId,listing.match_status==="matched"?listing.product_id:null,source.id,listing.id,listing.match_id,source.channel,listing.seller_name||source.name,listing.external_listing_id,listing.current_price,listing.currency,ref,hash,Number(current?.version||0)+1,observedAt])).rows[0];}const key=`${listing.id}:out_of_stock:${observedAt.toISOString().slice(0,10)}`;await client.query(`INSERT INTO volt_price.market_signals(tenant_id,source_id,listing_id,product_id,source_observation_id,signal_type,severity,dedupe_key,observed_at,evidence) VALUES($1,$2,$3,$4,$5,'out_of_stock','opportunity',$6,$7,$8::jsonb) ON CONFLICT(tenant_id,dedupe_key) DO NOTHING`,[auth.tenantId,source.id,listing.id,listing.match_status==="matched"?listing.product_id:null,observation?.id||null,key,observedAt,JSON.stringify({before:{available:true},after:{available:false},reason:"missing_from_complete_snapshot"})]);output.push({listing:{...listing,available:false},match:null,observation,signals:[{type:"out_of_stock",severity:"opportunity"}],unchanged:false});}}
    const affectedProducts=[...new Set(output.map((row)=>row.match?.status==="matched"?row.match.product_id:row.listing?.match_status==="matched"?row.listing.product_id:null).filter(Boolean))];for(const productId of affectedProducts){const product=products.find((row)=>row.id===productId);const ownPrice=product?.current_price??product?.metadata?.currentPrice??product?.metadata?.current_price??null;if(ownPrice===null||ownPrice===undefined)continue;const rows=(await client.query(`SELECT l.current_price observed_price,l.available FROM volt_price.competitor_listings l JOIN volt_price.market_matches m ON m.listing_id=l.id WHERE m.product_id=$1 AND m.status='matched'`,[productId])).rows;const market=summarizeProductMarket(rows,ownPrice);if(["above_market","below_market"].includes(market.range.position)){const type=market.range.position;const key=`product:${productId}:${type}:${observedAt.toISOString().slice(0,10)}`;await client.query(`INSERT INTO volt_price.market_signals(tenant_id,source_id,product_id,signal_type,severity,dedupe_key,observed_at,value,evidence) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb) ON CONFLICT(tenant_id,dedupe_key) DO UPDATE SET value=EXCLUDED.value,evidence=EXCLUDED.evidence,updated_at=now()`,[auth.tenantId,source.id,productId,type,type==="above_market"?"warning":"opportunity",key,observedAt,market.range.ownVsMedian,JSON.stringify({ownPrice,range:market.range,availableCompetitors:market.availableCompetitors})]);}}
    await client.query("UPDATE volt_price.market_sources SET status='active',last_sync_at=now(),last_success_at=now(),last_error=NULL,updated_at=now() WHERE id=$1",[source.id]);await log(client,auth,request,"market.listings.import","market_source",source.id,{count:output.length,unchanged:output.filter((row)=>row.unchanged).length,fullSnapshot:Boolean(options.fullSnapshot)});return output;
  });}

async function syncMeliSource(auth,sourceId,input={},request=null){const source=await withTenant(auth.tenantId,auth.userId,(client)=>visible(client,"market_sources",sourceId,"Fonte"));if(source.channel!=="meli"||source.source_kind!=="official_api")invalid("Fonte nao e um conector oficial Mercado Livre.");if(!source.external_seller_id&&!source.external_seller_name)invalid("Fonte Mercado Livre exige seller ID ou nickname.");const maxPages=Math.min(20,Math.max(1,Number(input.maxPages)||5));const all=[];let complete=false;try{for(let page=0;page<maxPages;page++){const data=await meli.searchSellerListings(auth,{siteId:source.site_id||"MLB",sellerId:source.external_seller_id,nickname:source.external_seller_name,offset:page*50,limit:50,connectionId:source.connection_id});const rows=Array.isArray(data.results)?data.results:[];all.push(...rows.map(normalizeMeliListing));const total=Number(data.paging?.total||all.length);if(!rows.length||all.length>=total){complete=true;break;}}return await importListings(auth,source.id,all,{normalized:true,sourceType:"API",observedAt:input.observedAt,fullSnapshot:complete},request);}catch(error){await withTenant(auth.tenantId,auth.userId,(client)=>client.query("UPDATE volt_price.market_sources SET status='error',last_sync_at=now(),last_error=$2,updated_at=now() WHERE id=$1",[source.id,clean(error.message,1000)]));throw error;}}

async function reviewMatch(auth,matchId,input={},request=null){const status=clean(input.status,20);if(!["matched","rejected","unmatched"].includes(status))invalid("Status de revisao invalido.");return withTenant(auth.tenantId,auth.userId,async(client)=>{const before=await visible(client,"market_matches",matchId,"Match");if(status==="matched")await visible(client,"products",input.productId,"Produto");const row=(await client.query("UPDATE volt_price.market_matches SET product_id=$2,status=$3,confidence=$4,reason=$5,reviewed_by=$6,reviewed_at=now(),updated_at=now() WHERE id=$1 RETURNING *",[before.id,status==="matched"?input.productId:null,status,status==="matched"?1:0,status==="matched"?"manual_review_approved":"manual_review_rejected",auth.userId])).rows[0];await client.query("UPDATE volt_price.market_observations SET product_id=$2,match_id=$3,updated_at=now() WHERE listing_id=$1 AND is_current",[row.listing_id,row.product_id,row.id]);await log(client,auth,request,"market.match.review","market_match",row.id,{before:{status:before.status,productId:before.product_id},after:{status:row.status,productId:row.product_id}});return row;});}

async function updateSignal(auth,signalId,input={},request=null){const status=clean(input.status,30);if(!["acknowledged","resolved","ignored","open"].includes(status))invalid("Status do sinal invalido.");return withTenant(auth.tenantId,auth.userId,async(client)=>{const signal=await visible(client,"market_signals",signalId,"Sinal");const row=(await client.query("UPDATE volt_price.market_signals SET status=$2,resolved_at=CASE WHEN $2 IN ('resolved','ignored') THEN now() ELSE NULL END,updated_at=now() WHERE id=$1 RETURNING *",[signal.id,status])).rows[0];await log(client,auth,request,"market.signal.update","market_signal",row.id,{status});return row;});}

module.exports={marketOverview,upsertSource,importListings,syncMeliSource,reviewMatch,updateSignal};
