"use strict";
const express = require("express");
const controller = require("../controllers/financialController");
const router = express.Router();
router.get("/costs", controller.costs);
router.get("/costs/export", controller.exportCosts);
router.post("/costs/import", controller.importCosts);
router.get("/costs/history/:sku", controller.costHistory);
router.put("/costs/:sku", controller.saveCost);
router.get("/tax", controller.getTax);
router.put("/tax", controller.saveTax);
router.get("/margins", controller.margins);
router.get("/calculator/lookup", controller.lookup);
router.post("/calculator/calculate", controller.calculate);
module.exports = router;
