"use strict";
const express=require("express");
const controller=require("../controllers/uxAnalyticsController");
const router=express.Router();
router.get("/stock",controller.stock);
router.get("/costs",controller.costs);
router.get("/margins",controller.margins);
router.post("/margins/sync",controller.syncMargins);
router.get("/equilibrium",controller.equilibrium);
module.exports=router;
