BEGIN;

INSERT INTO ml.auth_audit_retention_rules (evento, descricao, retention_days)
VALUES
  ('account_selected', 'Selecao manual da conta ativa', 120),
  ('account_selection_cleared', 'Limpeza manual da conta ativa', 120),
  ('admin_backup_exported', 'Exportacao de backup pelo painel administrativo', 365),
  ('admin_backup_imported', 'Importacao de backup pelo painel administrativo', 365),
  ('admin_company_created', 'Criacao de empresa no painel administrativo', 365),
  ('admin_company_deleted', 'Remocao de empresa no painel administrativo', 365),
  ('admin_company_link_created', 'Criacao de vinculo entre usuario e empresa', 365),
  ('admin_company_link_deleted', 'Remocao de vinculo entre usuario e empresa', 365),
  ('admin_company_link_updated', 'Edicao de vinculo entre usuario e empresa', 365),
  ('admin_company_updated', 'Atualizacao de empresa no painel administrativo', 365),
  ('admin_meli_account_created', 'Cadastro manual de conta Mercado Livre', 365),
  ('admin_meli_account_deleted', 'Remocao manual de conta Mercado Livre', 365),
  ('admin_meli_account_revoked', 'Revogacao manual de autorizacao de conta Mercado Livre', 365),
  ('admin_meli_account_updated', 'Atualizacao manual de conta Mercado Livre', 365),
  ('admin_meli_token_deleted', 'Remocao manual de token Mercado Livre', 365),
  ('admin_migrations_run', 'Execucao manual de migracoes pelo painel', 365),
  ('admin_oauth_state_deleted', 'Remocao manual de registro OAuth state', 365),
  ('admin_oauth_states_cleanup', 'Limpeza manual de registros OAuth state', 365),
  ('admin_user_created', 'Criacao de usuario no painel administrativo', 365),
  ('admin_user_deleted', 'Remocao de usuario no painel administrativo', 365),
  ('admin_user_invite_resent', 'Reenvio de convite de ativacao para usuario', 365),
  ('admin_user_updated', 'Atualizacao de usuario no painel administrativo', 365),
  ('dimensions_validation_bulk_started', 'Inicio de validacao em lote de dimensoes', 180),
  ('dimensions_validation_job_canceled', 'Cancelamento de job de validacao de dimensoes', 180),
  ('dimensions_validation_results_downloaded', 'Download de resultados da validacao de dimensoes', 120),
  ('dimensions_validation_single_requested', 'Validacao individual de dimensoes', 180),
  ('listing_deleted_bulk_canceled', 'Cancelamento de job de exclusao em lote', 180),
  ('listing_activated_bulk_started', 'Inicio de ativacao em lote de anuncios', 180),
  ('listing_closed_bulk_started', 'Inicio de encerramento em lote de anuncios', 180),
  ('listing_management_cancel_request_received', 'Requisicao de cancelamento recebida na Gestao de Anuncios', 365),
  ('listing_management_item_processed', 'Resultado individual de item na Gestao de Anuncios', 365),
  ('listing_management_job_cancel_rejected', 'Cancelamento recusado na Gestao de Anuncios', 365),
  ('listing_management_job_cancel_requested', 'Solicitacao de cancelamento na Gestao de Anuncios', 365),
  ('listing_management_job_canceled', 'Job cancelado na Gestao de Anuncios', 365),
  ('listing_management_job_completed', 'Conclusao de job na Gestao de Anuncios', 365),
  ('listing_management_job_failed', 'Falha de job na Gestao de Anuncios', 365),
  ('listing_management_job_processing_started', 'Inicio efetivo de processamento na Gestao de Anuncios', 365),
  ('listing_management_results_downloaded', 'Download de resultados da Gestao de Anuncios', 365),
  ('listing_deleted_bulk_started', 'Inicio de exclusao em lote de anuncios', 180),
  ('listing_deleted_single', 'Exclusao individual de anuncio', 180),
  ('listing_filter_job_canceled', 'Cancelamento de job do filtro avancado de anuncios', 180),
  ('listing_filter_job_started', 'Inicio de job do filtro avancado de anuncios', 180),
  ('listing_filter_results_downloaded', 'Download de resultados do filtro avancado de anuncios', 120),
  ('listing_pause_relisted_bulk_started', 'Inicio de pausa e relistagem em lote de anuncios', 180),
  ('listing_paused_bulk_started', 'Inicio de pausa em lote de anuncios', 180),
  ('listing_relisted_bulk_started', 'Inicio de relistagem em lote de anuncios', 180),
  ('meli_account_selected', 'Selecao da conta Mercado Livre ativa', 120),
  ('meli_account_selection_cleared', 'Limpeza da selecao da conta Mercado Livre ativa', 120),
  ('meli_oauth_callback', 'Retorno do fluxo OAuth do Mercado Livre', 180),
  ('meli_oauth_started', 'Inicio do fluxo OAuth do Mercado Livre', 180),
  ('model_mass_apply_started', 'Inicio da aplicacao em massa de modelo', 180),
  ('model_mass_job_canceled', 'Cancelamento de job de modelo em massa', 180),
  ('model_mass_preview_requested', 'Geracao de preview de modelo em massa', 120),
  ('production_time_bulk_started', 'Inicio da alteracao em lote de prazo de producao', 180),
  ('production_time_job_canceled', 'Cancelamento de job de prazo de producao', 180),
  ('production_time_single_updated', 'Alteracao individual de prazo de producao', 180),
  ('promotion_apply_manual', 'Aplicacao manual de promocao', 180),
  ('promotion_apply_mass_started', 'Inicio da aplicacao em massa de promocao', 180),
  ('promotion_apply_single_item', 'Aplicacao de promocao em item unico', 180),
  ('promotion_bulk_apply_started', 'Inicio de job de aplicacao em lote de promocao', 180),
  ('promotion_bulk_prepare', 'Preparacao de lote para promocao', 120),
  ('promotion_bulk_remove_started', 'Inicio de remocao em lote de promocao', 180),
  ('promotion_created', 'Criacao de promocao', 180),
  ('promotion_deleted', 'Remocao de promocao', 180),
  ('promotion_legacy_bulk_started', 'Inicio de lote pela rota legada de criacao de promocao', 180),
  ('promotion_legacy_job_downloaded', 'Download de resultado pela rota legada de criacao de promocao', 120),
  ('promotion_legacy_single_started', 'Inicio de promocao individual pela rota legada', 180),
  ('promotion_item_processed', 'Resultado individual de item em operacao de promocao', 365),
  ('promotion_job_cancel_rejected', 'Cancelamento recusado em job de promocao', 365),
  ('promotion_job_cancel_requested', 'Solicitacao de cancelamento em job de promocao', 365),
  ('promotion_job_canceled', 'Job de promocao cancelado', 365),
  ('promotion_job_completed', 'Conclusao de job de promocao', 365),
  ('promotion_job_failed', 'Falha de job de promocao', 365),
  ('promotion_job_processing_started', 'Inicio efetivo de processamento em job de promocao', 365),
  ('promotion_job_results_downloaded', 'Download de resultados de job de promocao', 365),
  ('promotion_remove_bulk_started', 'Inicio de remocao em lote de promocao pela tela legada', 180),
  ('promotion_remove_single_requested', 'Remocao individual de promocao pela tela legada', 180),
  ('promotion_selection_prepare', 'Preparacao da selecao de itens para promocao', 120),
  ('promotion_updated', 'Atualizacao de promocao', 180),
  ('token_access_requested', 'Solicitacao de leitura do token de acesso', 180),
  ('token_initial_requested', 'Solicitacao inicial de token', 180),
  ('token_renew_requested', 'Solicitacao de renovacao de token', 180),
  ('wholesale_price_apply_started', 'Inicio da aplicacao em massa de preco de atacado', 180),
  ('wholesale_price_job_canceled', 'Cancelamento de job de preco de atacado', 180)
ON CONFLICT (evento) DO NOTHING;

COMMIT;
