"use strict";
const crypto=require("crypto");
const {config,baseUrl,publicPath}=require("../config");
const {fetchJson}=require("./http");
const {getConnection,tokenValues,upsertConnection,markConnectionError}=require("./tokenStore");
const {withTenant}=require("../db");
const positive=(value)=>/^\d+$/.test(String(value||""))&&Number(value)>0;
function tokenData(data,fallback=14400){if(data?.error)throw Object.assign(new Error("Shopee recusou a operacao."),{statusCode:400,code:String(data.error)});const payload=data?.response&&typeof data.response==="object"?data.response:data?.data&&typeof data.data==="object"?data.data:data;const expiresIn=Number(payload?.expire_in||fallback),refreshExpiresIn=Number(payload?.refresh_token_expire_in||payload?.refresh_expire_in||0);if(!payload?.access_token||!payload?.refresh_token||!Number.isFinite(expiresIn)||expiresIn<=0||!Number.isFinite(refreshExpiresIn)||refreshExpiresIn<0)throw Object.assign(new Error("Resposta de token Shopee invalida."),{statusCode:502,code:"shopee_token_response_invalid"});return{accessToken:String(payload.access_token),refreshToken:String(payload.refresh_token),expiresIn,refreshExpiresIn};}
function createShopeeClient({shopeeConfig=config.shopee,getConnectionFn=getConnection,tokenValuesFn=tokenValues,upsertConnectionFn=upsertConnection,markConnectionErrorFn=markConnectionError,withTenantFn=withTenant,fetchJsonFn=fetchJson,baseUrlFn=baseUrl,clock=Date.now}={}){
 const now=()=>Number(clock()),timestamp=()=>Math.floor(now()/1000);
 const hmac=(base)=>{if(!shopeeConfig.partnerKey)throw Object.assign(new Error("SHOPEE_PARTNER_KEY nao configurada."),{statusCode:503});return crypto.createHmac("sha256",shopeeConfig.partnerKey).update(base).digest("hex");};
 const publicSign=(path,value)=>hmac(`${shopeeConfig.partnerId}${path}${value}`),shopSign=(path,value,access,shop)=>hmac(`${shopeeConfig.partnerId}${path}${value}${access}${shop}`);
 const callbackUrl=(req)=>`${baseUrlFn(req)}${publicPath("/api/integrations/shopee/callback")}`;
 function buildAuthUrl(req,state){if(!shopeeConfig.partnerId)throw Object.assign(new Error("SHOPEE_PARTNER_ID nao configurado."),{statusCode:503});if(!state)throw Object.assign(new Error("OAuth state Shopee ausente."),{statusCode:400});const value=timestamp(),path=shopeeConfig.authPartnerPath,url=new URL(`${shopeeConfig.apiBase}${path}`);url.searchParams.set("partner_id",shopeeConfig.partnerId);url.searchParams.set("timestamp",String(value));url.searchParams.set("sign",publicSign(path,value));url.searchParams.set("redirect",callbackUrl(req));url.searchParams.set("state",String(state));return url.toString();}
 async function tokenRequest(path,body){const value=timestamp(),url=new URL(`${shopeeConfig.apiBase}${path}`);url.searchParams.set("partner_id",shopeeConfig.partnerId);url.searchParams.set("timestamp",String(value));url.searchParams.set("sign",publicSign(path,value));return fetchJsonFn(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});}
 async function exchangeCode(code,shopId){if(!code||!positive(shopId))throw Object.assign(new Error("Callback Shopee invalido."),{statusCode:400});return tokenRequest(shopeeConfig.tokenPath,{code:String(code),shop_id:Number(shopId),partner_id:Number(shopeeConfig.partnerId)});}
 async function refreshLocked(auth,connectionId){if(!connectionId)throw Object.assign(new Error("Conexao Shopee obrigatoria."),{statusCode:409,code:"shopee_connection_required"});try{const connectionVersion=(value)=>[value?.updated_at?new Date(value.updated_at).getTime():"",value?.token_cipher||"",value?.refresh_token_cipher||""].join("|");const observed=await getConnectionFn(auth,"shopee",connectionId);const observedExpiry=observed?.token_expires_at?new Date(observed.token_expires_at).getTime():null;const observedVersion=connectionVersion(observed);return await withTenantFn(auth.tenantId,auth.userId,async(client)=>{const row=await getConnectionFn(auth,"shopee",connectionId,{forUpdate:true,client});if(!row)throw Object.assign(new Error("Shopee nao conectada."),{statusCode:404,code:"shopee_not_connected"});const currentExpiry=row.token_expires_at?new Date(row.token_expires_at).getTime():null;const currentVersion=connectionVersion(row);if(currentExpiry&&currentExpiry>now()+5*60_000&&((observedExpiry&&currentExpiry>observedExpiry)||currentVersion!==observedVersion))return row;const {refreshToken}=tokenValuesFn(row)||{};if(!refreshToken||(row.refresh_expires_at&&new Date(row.refresh_expires_at).getTime()<=now()))throw Object.assign(new Error("A autorizacao Shopee precisa ser renovada."),{statusCode:409,code:"reauthorization_required"});const shopId=String(row.external_account_id||"");if(!positive(shopId))throw Object.assign(new Error("Conexao Shopee invalida."),{statusCode:409,code:"reauthorization_required"});let tokens;try{tokens=tokenData(await tokenRequest(shopeeConfig.refreshPath,{refresh_token:refreshToken,shop_id:Number(shopId),partner_id:Number(shopeeConfig.partnerId)}));}catch(error){if(/token|auth|refresh|expired/i.test(String(error?.code||"")))throw Object.assign(new Error("A autorizacao Shopee precisa ser renovada."),{statusCode:409,code:"reauthorization_required"});throw error;}return upsertConnectionFn(client,auth.tenantId,"shopee",{status:"active",displayName:row.display_name||`Shopee ${shopId}`,externalAccountId:shopId,apiBaseUrl:shopeeConfig.apiBase,accessToken:tokens.accessToken,refreshToken:tokens.refreshToken,tokenExpiresAt:new Date(now()+tokens.expiresIn*1000),refreshExpiresAt:tokens.refreshExpiresIn>0?new Date(now()+tokens.refreshExpiresIn*1000):null,metadata:{...(row.metadata||{}),partner_id:String(shopeeConfig.partnerId),shop_id:shopId},lastRefreshAt:new Date(now())});});}catch(error){if(error?.code==="reauthorization_required")await markConnectionErrorFn(auth,connectionId,"reauthorization_required").catch(()=>{});throw error;}}
 async function validConnection(auth,connectionId){if(!connectionId)throw Object.assign(new Error("Conexao Shopee obrigatoria."),{statusCode:409,code:"shopee_connection_required"});let row=await getConnectionFn(auth,"shopee",connectionId);if(!row)throw Object.assign(new Error("Shopee nao conectada."),{statusCode:409,code:"shopee_not_connected"});if(!row.token_expires_at||new Date(row.token_expires_at).getTime()<now()+5*60_000)row=await refreshLocked(auth,row.id);return row;}
 async function shopeeCall(auth,path,params={},connectionId,retried=false){const row=await validConnection(auth,connectionId),{accessToken}=tokenValuesFn(row)||{},shopId=String(row.external_account_id||"");if(!accessToken||!positive(shopId))throw Object.assign(new Error("Conexao Shopee invalida."),{statusCode:409,code:"shopee_not_connected"});const value=timestamp(),url=new URL(`${shopeeConfig.apiBase}${path}`);url.searchParams.set("partner_id",shopeeConfig.partnerId);url.searchParams.set("timestamp",String(value));url.searchParams.set("access_token",accessToken);url.searchParams.set("shop_id",shopId);url.searchParams.set("sign",shopSign(path,value,accessToken,Number(shopId)));Object.entries(params).forEach(([key,value])=>{if(value!==undefined&&value!==null&&value!=="")url.searchParams.set(key,String(value));});let data;try{data=await fetchJsonFn(url);}catch(error){if(!retried&&(error?.upstreamStatus===401||/token/i.test(String(error?.message||"")))){const refreshed=await refreshLocked(auth,row.id);return shopeeCall(auth,path,params,refreshed.id,true);}throw error;}if(data?.error){if(!retried&&/access.?token|token/i.test(`${data.error||""}${data.message||""}`)){const refreshed=await refreshLocked(auth,row.id);return shopeeCall(auth,path,params,refreshed.id,true);}throw Object.assign(new Error("Shopee recusou a operacao."),{statusCode:400,code:String(data.error)});}return data;}
 const pick=(source,...keys)=>{for(const key of keys)if(source&&source[key]!==undefined&&source[key]!==null)return Number(source[key])||0;return 0;};
 function normalizeEscrow(raw,orderSn){const data=raw?.response?.order_income||raw?.response||raw?.order_income||raw||{},summary={commissionFee:pick(data,"commission_fee"),serviceFee:pick(data,"service_fee"),sellerTransactionFee:pick(data,"seller_transaction_fee","transaction_fee"),sellerVoucher:pick(data,"seller_voucher"),sellerCoinCashback:pick(data,"seller_coin_cash_back","seller_coin_cashback"),actualShippingFee:pick(data,"actual_shipping_fee"),shopeeShippingRebate:pick(data,"shopee_shipping_rebate"),escrowAmount:pick(data,"escrow_amount","seller_income")};summary.totalKnownPlatformFees=summary.commissionFee+summary.serviceFee+summary.sellerTransactionFee;return{channel:"shopee",orderId:String(orderSn),summary,raw};}
 const orderFees=async(auth,orderSn,connectionId)=>normalizeEscrow(await shopeeCall(auth,shopeeConfig.escrowPath,{order_sn:orderSn},connectionId),orderSn);
 async function listOrders(auth,{from,to,cursor="",pageSize=50,timeRangeField="create_time",connectionId}={}){const current=Math.floor(now()/1000),fromTs=from?Math.floor(new Date(`${from}T00:00:00-03:00`).getTime()/1000):current-14*86400,toTs=to?Math.floor(new Date(`${to}T23:59:59-03:00`).getTime()/1000):current;const field=timeRangeField==="update_time"?"update_time":"create_time";return shopeeCall(auth,shopeeConfig.orderListPath,{time_range_field:field,time_from:fromTs,time_to:toTs,page_size:Math.min(100,Number(pageSize)||50),cursor},connectionId);}
 const orderDetail=(auth,orderSnList,connectionId)=>shopeeCall(auth,shopeeConfig.orderDetailPath,{order_sn_list:Array.isArray(orderSnList)?orderSnList.join(","):String(orderSnList),response_optional_fields:"estimated_shipping_fee,actual_shipping_fee,item_list,pay_time,checkout_shipping_carrier,reverse_shipping_fee_order_flag"},connectionId);
 return{callbackUrl,buildAuthUrl,exchangeCode,refreshLocked,validConnection,orderFees,listOrders,orderDetail,normalizeEscrow};
}
const defaultShopeeClient=createShopeeClient();
module.exports={...defaultShopeeClient,createShopeeClient,normalizeTokenResponse:tokenData,validPositiveInteger:positive};
