"use strict";
const db=require("../config/postgres");const {decryptSecret}=require("../services/tokenCipher");
async function findSubscriptionSecrets({tenantId,topic}){const rows=(await db.query(`select id,secret_ciphertext,previous_secret_ciphertext,previous_secret_expires_at from magalu.webhook_subscriptions where magalu_tenant_id=$1 and topic=$2 and status='active' order by updated_at desc limit 5`,[String(tenantId),String(topic)])).rows;const secrets=[];for(const row of rows){if(row.secret_ciphertext)secrets.push({subscriptionId:row.id,secret:decryptSecret(row.secret_ciphertext),kind:"current"});if(row.previous_secret_ciphertext&&row.previous_secret_expires_at&&new Date(row.previous_secret_expires_at).getTime()>Date.now())secrets.push({subscriptionId:row.id,secret:decryptSecret(row.previous_secret_ciphertext),kind:"previous"});}return secrets.filter(r=>r.secret);}
async function insertValidatedEvent({tenantId,topic,payload,rawBody,eventHash,signature,timestamp}){const result=await db.query(`with inserted as (insert into magalu.webhook_events(magalu_tenant_id,topic,payload,raw_body,event_hash,signature_header,timestamp_header,processing_status) values($1,$2,$3::jsonb,$4,$5,$6,$7,'validated') on conflict(event_hash) do nothing returning id,processing_status,true as inserted) select id,processing_status,inserted from inserted union all select id,processing_status,false as inserted from magalu.webhook_events where event_hash=$5 and not exists(select 1 from inserted) limit 1`,[String(tenantId),String(topic),JSON.stringify(payload),rawBody,eventHash,signature,timestamp]);return result.rows[0]||null;}
async function markEventQueued(eventId){await db.query(`update magalu.webhook_events set processing_status='queued' where id=$1 and processing_status in('validated','failed')`,[Number(eventId)]);}
async function claimEvent(eventId){return db.withClient(async(client)=>{await client.query("begin");try{const row=(await client.query(`select id,account_id,magalu_tenant_id,topic,payload,processing_status,attempts from magalu.webhook_events where id=$1 and processing_status in('queued','validated','failed') for update skip locked`,[Number(eventId)])).rows[0]||null;if(!row){await client.query("commit");return null;}await client.query(`update magalu.webhook_events set processing_status='processing',attempts=attempts+1 where id=$1`,[Number(eventId)]);await client.query("commit");return row;}catch(error){await client.query("rollback").catch(()=>{});throw error;}});}
async function attachEventAccount(eventId,accountId){await db.query(`update magalu.webhook_events set account_id=$2 where id=$1`,[Number(eventId),Number(accountId)]);}
async function markEventProcessed(eventId){await db.query(`update magalu.webhook_events set processing_status='processed',processed_at=now(),last_error=null where id=$1`,[Number(eventId)]);}
async function markEventIgnored(eventId,reason){await db.query(`update magalu.webhook_events set processing_status='ignored',processed_at=now(),last_error=$2 where id=$1`,[Number(eventId),String(reason||"ignored").slice(0,2000)]);}
async function markEventFailed(eventId,error){await db.query(`update magalu.webhook_events set processing_status='failed',last_error=$2 where id=$1`,[Number(eventId),String(error||"webhook_processing_failed").slice(0,2000)]);}
async function listSubscriptionsForAccount(accountId){const {rows}=await db.query(`select id,topic,webhook_url,status,subscription_external_id,last_synced_at,updated_at from magalu.webhook_subscriptions where account_id=$1 order by topic asc,updated_at desc`,[Number(accountId)]);return rows;}
module.exports={findSubscriptionSecrets,insertValidatedEvent,markEventQueued,claimEvent,attachEventAccount,markEventProcessed,markEventIgnored,markEventFailed,listSubscriptionsForAccount};
