"use strict";
require("../src/loadEnv").loadLocalEnv();
const fs=require("fs");const path=require("path");const crypto=require("crypto");const {Client}=require("pg");
const directDatabaseUrl=process.env.DB_VOLTPRICE_DIRECT||process.env.VOLT_PRICE_DIRECT_DATABASE_URL;
const localFallback=String(process.env.NODE_ENV||"").toLowerCase()!=="production"?(process.env.DB_VOLTPRICE||process.env.VOLT_PRICE_DATABASE_URL||process.env.DATABASE_URL):"";
const databaseUrl=directDatabaseUrl||localFallback;
if(!databaseUrl){console.error("[VoltPrice] DB_VOLTPRICE_DIRECT/VOLT_PRICE_DIRECT_DATABASE_URL nao configurada para migrations.");process.exit(1);}
function ssl(url){if(/sslmode=disable(?:&|$)/i.test(String(url||"")))return false;return String(process.env.NODE_ENV||"").toLowerCase()==="production"||/sslmode=require/i.test(String(url||""));}
async function main(){if(!databaseUrl){console.warn("[VoltPrice] Banco nao configurado; migrations ignoradas.");return;}const client=new Client({connectionString:databaseUrl,ssl:ssl(databaseUrl)?{rejectUnauthorized:false}:false});await client.connect();try{await client.query("SELECT pg_advisory_lock(hashtext('volt_price_migrations'))");await client.query("CREATE SCHEMA IF NOT EXISTS volt_price");await client.query(`CREATE TABLE IF NOT EXISTS volt_price.migrations(id bigserial primary key,filename text not null unique,checksum text,applied_at timestamptz not null default now())`);const files=fs.readdirSync(__dirname).filter(f=>/^\d+_.*\.sql$/i.test(f)).sort();for(const file of files){const sqlText=fs.readFileSync(path.join(__dirname,file),"utf8").replace(/\r\n/g,"\n");const checksum=crypto.createHash("sha256").update(sqlText).digest("hex");const prev=(await client.query("SELECT checksum FROM volt_price.migrations WHERE filename=$1",[file])).rows[0];if(prev){if(prev.checksum&&prev.checksum!==checksum)throw new Error(`Migration VoltPrice alterada depois de aplicada: ${file}`);continue;}console.log(`[VoltPrice] Aplicando ${file}`);await client.query("BEGIN");try{await client.query(sqlText);await client.query("INSERT INTO volt_price.migrations(filename,checksum) VALUES($1,$2)",[file,checksum]);await client.query("COMMIT");}catch(e){await client.query("ROLLBACK");throw e;}}}finally{await client.query("SELECT pg_advisory_unlock(hashtext('volt_price_migrations'))").catch(()=>{});await client.end();}}
main().catch(e=>{console.error("[VoltPrice] Migration falhou:",e);process.exit(1);});
